//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.13 at 06:10:25 PM IST 
//


package com.cbs.ibl.pojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Transaction">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="IBLRefNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="CustomerRefNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="StatusCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="StatusDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="UTR" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Amount" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="TranType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="PaymentDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "transaction"
})
@XmlRootElement(name = "PaymentEnqResp")
public class PaymentEnqResp {

    @XmlElement(name = "Transaction", required = true)
    protected PaymentEnqResp.Transaction transaction;

    /**
     * Gets the value of the transaction property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentEnqResp.Transaction }
     *     
     */
    public PaymentEnqResp.Transaction getTransaction() {
        return transaction;
    }

    /**
     * Sets the value of the transaction property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentEnqResp.Transaction }
     *     
     */
    public void setTransaction(PaymentEnqResp.Transaction value) {
        this.transaction = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="IBLRefNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="CustomerRefNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="StatusCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="StatusDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="UTR" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Amount" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="TranType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="PaymentDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "iblRefNo",
        "customerRefNo",
        "statusCode",
        "statusDesc",
        "utr",
        "amount",
        "tranType",
        "paymentDate"
    })
    public static class Transaction {

        @XmlElement(name = "IBLRefNo", required = true)
        protected String iblRefNo;
        @XmlElement(name = "CustomerRefNo", required = true)
        protected String customerRefNo;
        @XmlElement(name = "StatusCode", required = true)
        protected String statusCode;
        @XmlElement(name = "StatusDesc", required = true)
        protected String statusDesc;
        @XmlElement(name = "UTR", required = true)
        protected String utr;
        @XmlElement(name = "Amount")
        protected byte amount;
        @XmlElement(name = "TranType", required = true)
        protected String tranType;
        @XmlElement(name = "PaymentDate", required = true)
        protected String paymentDate;

        /**
         * Gets the value of the iblRefNo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIBLRefNo() {
            return iblRefNo;
        }

        /**
         * Sets the value of the iblRefNo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIBLRefNo(String value) {
            this.iblRefNo = value;
        }

        /**
         * Gets the value of the customerRefNo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCustomerRefNo() {
            return customerRefNo;
        }

        /**
         * Sets the value of the customerRefNo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCustomerRefNo(String value) {
            this.customerRefNo = value;
        }

        /**
         * Gets the value of the statusCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStatusCode() {
            return statusCode;
        }

        /**
         * Sets the value of the statusCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStatusCode(String value) {
            this.statusCode = value;
        }

        /**
         * Gets the value of the statusDesc property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStatusDesc() {
            return statusDesc;
        }

        /**
         * Sets the value of the statusDesc property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStatusDesc(String value) {
            this.statusDesc = value;
        }

        /**
         * Gets the value of the utr property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUTR() {
            return utr;
        }

        /**
         * Sets the value of the utr property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUTR(String value) {
            this.utr = value;
        }

        /**
         * Gets the value of the amount property.
         * 
         */
        public byte getAmount() {
            return amount;
        }

        /**
         * Sets the value of the amount property.
         * 
         */
        public void setAmount(byte value) {
            this.amount = value;
        }

        /**
         * Gets the value of the tranType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTranType() {
            return tranType;
        }

        /**
         * Sets the value of the tranType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTranType(String value) {
            this.tranType = value;
        }

        /**
         * Gets the value of the paymentDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPaymentDate() {
            return paymentDate;
        }

        /**
         * Sets the value of the paymentDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPaymentDate(String value) {
            this.paymentDate = value;
        }

    }

}
