//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.10 at 07:04:01 PM IST 
//


package com.cbs.pojo.cpsms.transactionsdatarequest;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.cpsms.transactionsdatarequest package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TransactionDetailsAccountTransactionChannelType_QNAME = new QName("http://cpsms.com/TransactionsDataRequest", "ChannelType");
    private final static QName _TransactionDetailsAccountTransactionDrCrAccountNumber_QNAME = new QName("http://cpsms.com/TransactionsDataRequest", "DrCrAccountNumber");
    private final static QName _TransactionDetailsAccountTransactionValueDate_QNAME = new QName("http://cpsms.com/TransactionsDataRequest", "ValueDate");
    private final static QName _TransactionDetailsAccountTransactionTranRefNo_QNAME = new QName("http://cpsms.com/TransactionsDataRequest", "TranRefNo");
    private final static QName _TransactionDetailsAccountTransactionDate_QNAME = new QName("http://cpsms.com/TransactionsDataRequest", "Date");
    private final static QName _TransactionDetailsAccountTransactionPostTranBal_QNAME = new QName("http://cpsms.com/TransactionsDataRequest", "PostTranBal");
    private final static QName _TransactionDetailsAccountTransactionRemarks_QNAME = new QName("http://cpsms.com/TransactionsDataRequest", "Remarks");
    private final static QName _TransactionDetailsAccountTransactionCPSMSTransactionId_QNAME = new QName("http://cpsms.com/TransactionsDataRequest", "CPSMSTransactionId");
    private final static QName _TransactionDetailsAccountTransactionNarratives_QNAME = new QName("http://cpsms.com/TransactionsDataRequest", "Narratives");
    private final static QName _TransactionDetailsAccountTransactionTransactionType_QNAME = new QName("http://cpsms.com/TransactionsDataRequest", "TransactionType");
    private final static QName _TransactionDetailsAccountTransactionInstrumentDate_QNAME = new QName("http://cpsms.com/TransactionsDataRequest", "InstrumentDate");
    private final static QName _TransactionDetailsAccountTransactionDrCrAccountName_QNAME = new QName("http://cpsms.com/TransactionsDataRequest", "DrCrAccountName");
    private final static QName _TransactionDetailsAccountTransactionDrCrBnkNm_QNAME = new QName("http://cpsms.com/TransactionsDataRequest", "DrCrBnkNm");
    private final static QName _TransactionDetailsAccountTransactionDrCrBnkBrCd_QNAME = new QName("http://cpsms.com/TransactionsDataRequest", "DrCrBnkBrCd");
    private final static QName _TransactionDetailsAccountTransactionTransactionCategory_QNAME = new QName("http://cpsms.com/TransactionsDataRequest", "TransactionCategory");
    private final static QName _TransactionDetailsAccountTransactionAmount_QNAME = new QName("http://cpsms.com/TransactionsDataRequest", "Amount");
    private final static QName _TransactionDetailsAccountTransactionInstrumentNo_QNAME = new QName("http://cpsms.com/TransactionsDataRequest", "InstrumentNo");
    private final static QName _TransactionDetailsAccountTransactionUniqueTransactionNumber_QNAME = new QName("http://cpsms.com/TransactionsDataRequest", "UniqueTransactionNumber");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.cpsms.transactionsdatarequest
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TransactionDetails }
     * 
     */
    public TransactionDetails createTransactionDetails() {
        return new TransactionDetails();
    }

    /**
     * Create an instance of {@link TransactionDetails.Account }
     * 
     */
    public TransactionDetails.Account createTransactionDetailsAccount() {
        return new TransactionDetails.Account();
    }

    /**
     * Create an instance of {@link TransactionDetails.Account.Transaction }
     * 
     */
    public TransactionDetails.Account.Transaction createTransactionDetailsAccountTransaction() {
        return new TransactionDetails.Account.Transaction();
    }

    /**
     * Create an instance of {@link TransactionDetails.Account.Transaction.Narratives }
     * 
     */
    public TransactionDetails.Account.Transaction.Narratives createTransactionDetailsAccountTransactionNarratives() {
        return new TransactionDetails.Account.Transaction.Narratives();
    }

    /**
     * Create an instance of {@link TransactionDetails.Account.Transaction.Narratives.Narration }
     * 
     */
    public TransactionDetails.Account.Transaction.Narratives.Narration createTransactionDetailsAccountTransactionNarrativesNarration() {
        return new TransactionDetails.Account.Transaction.Narratives.Narration();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cpsms.com/TransactionsDataRequest", name = "ChannelType", scope = TransactionDetails.Account.Transaction.class)
    public JAXBElement<String> createTransactionDetailsAccountTransactionChannelType(String value) {
        return new JAXBElement<String>(_TransactionDetailsAccountTransactionChannelType_QNAME, String.class, TransactionDetails.Account.Transaction.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cpsms.com/TransactionsDataRequest", name = "DrCrAccountNumber", scope = TransactionDetails.Account.Transaction.class)
    public JAXBElement<String> createTransactionDetailsAccountTransactionDrCrAccountNumber(String value) {
        return new JAXBElement<String>(_TransactionDetailsAccountTransactionDrCrAccountNumber_QNAME, String.class, TransactionDetails.Account.Transaction.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cpsms.com/TransactionsDataRequest", name = "ValueDate", scope = TransactionDetails.Account.Transaction.class)
    public JAXBElement<String> createTransactionDetailsAccountTransactionValueDate(String value) {
        return new JAXBElement<String>(_TransactionDetailsAccountTransactionValueDate_QNAME, String.class, TransactionDetails.Account.Transaction.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cpsms.com/TransactionsDataRequest", name = "TranRefNo", scope = TransactionDetails.Account.Transaction.class)
    public JAXBElement<String> createTransactionDetailsAccountTransactionTranRefNo(String value) {
        return new JAXBElement<String>(_TransactionDetailsAccountTransactionTranRefNo_QNAME, String.class, TransactionDetails.Account.Transaction.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cpsms.com/TransactionsDataRequest", name = "Date", scope = TransactionDetails.Account.Transaction.class)
    public JAXBElement<String> createTransactionDetailsAccountTransactionDate(String value) {
        return new JAXBElement<String>(_TransactionDetailsAccountTransactionDate_QNAME, String.class, TransactionDetails.Account.Transaction.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cpsms.com/TransactionsDataRequest", name = "PostTranBal", scope = TransactionDetails.Account.Transaction.class)
    public JAXBElement<String> createTransactionDetailsAccountTransactionPostTranBal(String value) {
        return new JAXBElement<String>(_TransactionDetailsAccountTransactionPostTranBal_QNAME, String.class, TransactionDetails.Account.Transaction.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cpsms.com/TransactionsDataRequest", name = "Remarks", scope = TransactionDetails.Account.Transaction.class)
    public JAXBElement<String> createTransactionDetailsAccountTransactionRemarks(String value) {
        return new JAXBElement<String>(_TransactionDetailsAccountTransactionRemarks_QNAME, String.class, TransactionDetails.Account.Transaction.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cpsms.com/TransactionsDataRequest", name = "CPSMSTransactionId", scope = TransactionDetails.Account.Transaction.class)
    public JAXBElement<String> createTransactionDetailsAccountTransactionCPSMSTransactionId(String value) {
        return new JAXBElement<String>(_TransactionDetailsAccountTransactionCPSMSTransactionId_QNAME, String.class, TransactionDetails.Account.Transaction.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TransactionDetails.Account.Transaction.Narratives }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cpsms.com/TransactionsDataRequest", name = "Narratives", scope = TransactionDetails.Account.Transaction.class)
    public JAXBElement<TransactionDetails.Account.Transaction.Narratives> createTransactionDetailsAccountTransactionNarratives(TransactionDetails.Account.Transaction.Narratives value) {
        return new JAXBElement<TransactionDetails.Account.Transaction.Narratives>(_TransactionDetailsAccountTransactionNarratives_QNAME, TransactionDetails.Account.Transaction.Narratives.class, TransactionDetails.Account.Transaction.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cpsms.com/TransactionsDataRequest", name = "TransactionType", scope = TransactionDetails.Account.Transaction.class)
    public JAXBElement<String> createTransactionDetailsAccountTransactionTransactionType(String value) {
        return new JAXBElement<String>(_TransactionDetailsAccountTransactionTransactionType_QNAME, String.class, TransactionDetails.Account.Transaction.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cpsms.com/TransactionsDataRequest", name = "InstrumentDate", scope = TransactionDetails.Account.Transaction.class)
    public JAXBElement<String> createTransactionDetailsAccountTransactionInstrumentDate(String value) {
        return new JAXBElement<String>(_TransactionDetailsAccountTransactionInstrumentDate_QNAME, String.class, TransactionDetails.Account.Transaction.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cpsms.com/TransactionsDataRequest", name = "DrCrAccountName", scope = TransactionDetails.Account.Transaction.class)
    public JAXBElement<String> createTransactionDetailsAccountTransactionDrCrAccountName(String value) {
        return new JAXBElement<String>(_TransactionDetailsAccountTransactionDrCrAccountName_QNAME, String.class, TransactionDetails.Account.Transaction.class, value);
    }
    
    @XmlElementDecl(namespace = "http://cpsms.com/TransactionsDataRequest", name = "DrCrBnkNm", scope = TransactionDetails.Account.Transaction.class)
    public JAXBElement<String> createTransactionDetailsAccountTransactionDrCrBnkNm(String value) {
        return new JAXBElement<String>(_TransactionDetailsAccountTransactionDrCrBnkNm_QNAME, String.class, TransactionDetails.Account.Transaction.class, value);
    }
    
    @XmlElementDecl(namespace = "http://cpsms.com/TransactionsDataRequest", name = "DrCrBnkBrCd", scope = TransactionDetails.Account.Transaction.class)
    public JAXBElement<String> createTransactionDetailsAccountTransactionDrCrBnkBrCd(String value) {
        return new JAXBElement<String>(_TransactionDetailsAccountTransactionDrCrBnkBrCd_QNAME, String.class, TransactionDetails.Account.Transaction.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cpsms.com/TransactionsDataRequest", name = "TransactionCategory", scope = TransactionDetails.Account.Transaction.class)
    public JAXBElement<String> createTransactionDetailsAccountTransactionTransactionCategory(String value) {
        return new JAXBElement<String>(_TransactionDetailsAccountTransactionTransactionCategory_QNAME, String.class, TransactionDetails.Account.Transaction.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cpsms.com/TransactionsDataRequest", name = "Amount", scope = TransactionDetails.Account.Transaction.class)
    public JAXBElement<String> createTransactionDetailsAccountTransactionAmount(String value) {
        return new JAXBElement<String>(_TransactionDetailsAccountTransactionAmount_QNAME, String.class, TransactionDetails.Account.Transaction.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cpsms.com/TransactionsDataRequest", name = "InstrumentNo", scope = TransactionDetails.Account.Transaction.class)
    public JAXBElement<String> createTransactionDetailsAccountTransactionInstrumentNo(String value) {
        return new JAXBElement<String>(_TransactionDetailsAccountTransactionInstrumentNo_QNAME, String.class, TransactionDetails.Account.Transaction.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cpsms.com/TransactionsDataRequest", name = "UniqueTransactionNumber", scope = TransactionDetails.Account.Transaction.class)
    public JAXBElement<String> createTransactionDetailsAccountTransactionUniqueTransactionNumber(String value) {
        return new JAXBElement<String>(_TransactionDetailsAccountTransactionUniqueTransactionNumber_QNAME, String.class, TransactionDetails.Account.Transaction.class, value);
    }

}
