//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.26 at 05:18:51 PM IST 
//
package com.cbs.pojo.mms.pain009;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for Document complex type.
 *
 * <p>The following schema fragment specifies the expected content contained
 * within this class.
 *
 * <pre>
 * &lt;complexType name="Document">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MndtInitnReq" type="{urn:iso:std:iso:20022:tech:xsd:pain.009.001.01}MandateInitiationRequestV01"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlRootElement(name = "Document")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Document", propOrder = {
    "mndtInitnReq"
})
public class Document {

    @XmlElement(name = "MndtInitnReq", required = true)
    protected MandateInitiationRequestV01 mndtInitnReq;

    /**
     * Gets the value of the mndtInitnReq property.
     *
     * @return possible object is {@link MandateInitiationRequestV01 }
     *
     */
    public MandateInitiationRequestV01 getMndtInitnReq() {
        return mndtInitnReq;
    }

    /**
     * Sets the value of the mndtInitnReq property.
     *
     * @param value allowed object is {@link MandateInitiationRequestV01 }
     *
     */
    public void setMndtInitnReq(MandateInitiationRequestV01 value) {
        this.mndtInitnReq = value;
    }
}
