//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.13 at 06:10:25 PM IST 
//


package com.cbs.ibl.pojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RespCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RespDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Accounts">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="AccDtls">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="AccountNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="AccountName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="AvailableBalance" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="EffAvailableBalance" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="FDBalance" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ClearBalance" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="UnclearBalance" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "respCode",
    "respDesc",
    "accounts"
})
@XmlRootElement(name = "CustomerBalEnqResp")
public class CustomerBalEnqResp {

    @XmlElement(name = "RespCode", required = true)
    protected String respCode;
    @XmlElement(name = "RespDesc", required = true)
    protected String respDesc;
    @XmlElement(name = "Accounts", required = true)
    protected CustomerBalEnqResp.Accounts accounts;

    /**
     * Gets the value of the respCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRespCode() {
        return respCode;
    }

    /**
     * Sets the value of the respCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRespCode(String value) {
        this.respCode = value;
    }

    /**
     * Gets the value of the respDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRespDesc() {
        return respDesc;
    }

    /**
     * Sets the value of the respDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRespDesc(String value) {
        this.respDesc = value;
    }

    /**
     * Gets the value of the accounts property.
     * 
     * @return
     *     possible object is
     *     {@link CustomerBalEnqResp.Accounts }
     *     
     */
    public CustomerBalEnqResp.Accounts getAccounts() {
        return accounts;
    }

    /**
     * Sets the value of the accounts property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomerBalEnqResp.Accounts }
     *     
     */
    public void setAccounts(CustomerBalEnqResp.Accounts value) {
        this.accounts = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="AccDtls">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="AccountNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="AccountName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="AvailableBalance" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="EffAvailableBalance" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="FDBalance" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ClearBalance" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="UnclearBalance" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "accDtls"
    })
    public static class Accounts {

        @XmlElement(name = "AccDtls", required = true)
        protected CustomerBalEnqResp.Accounts.AccDtls accDtls;

        /**
         * Gets the value of the accDtls property.
         * 
         * @return
         *     possible object is
         *     {@link CustomerBalEnqResp.Accounts.AccDtls }
         *     
         */
        public CustomerBalEnqResp.Accounts.AccDtls getAccDtls() {
            return accDtls;
        }

        /**
         * Sets the value of the accDtls property.
         * 
         * @param value
         *     allowed object is
         *     {@link CustomerBalEnqResp.Accounts.AccDtls }
         *     
         */
        public void setAccDtls(CustomerBalEnqResp.Accounts.AccDtls value) {
            this.accDtls = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="AccountNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="AccountName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="AvailableBalance" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="EffAvailableBalance" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="FDBalance" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ClearBalance" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="UnclearBalance" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "accountNumber",
            "accountName",
            "availableBalance",
            "effAvailableBalance",
            "fdBalance",
            "clearBalance",
            "unclearBalance"
        })
        public static class AccDtls {

            @XmlElement(name = "AccountNumber", required = true)
            protected String accountNumber;
            @XmlElement(name = "AccountName", required = true)
            protected String accountName;
            @XmlElement(name = "AvailableBalance", required = true)
            protected String availableBalance;
            @XmlElement(name = "EffAvailableBalance", required = true)
            protected String effAvailableBalance;
            @XmlElement(name = "FDBalance", required = true)
            protected String fdBalance;
            @XmlElement(name = "ClearBalance", required = true)
            protected String clearBalance;
            @XmlElement(name = "UnclearBalance", required = true)
            protected String unclearBalance;

            /**
             * Gets the value of the accountNumber property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAccountNumber() {
                return accountNumber;
            }

            /**
             * Sets the value of the accountNumber property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAccountNumber(String value) {
                this.accountNumber = value;
            }

            /**
             * Gets the value of the accountName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAccountName() {
                return accountName;
            }

            /**
             * Sets the value of the accountName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAccountName(String value) {
                this.accountName = value;
            }

            /**
             * Gets the value of the availableBalance property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAvailableBalance() {
                return availableBalance;
            }

            /**
             * Sets the value of the availableBalance property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAvailableBalance(String value) {
                this.availableBalance = value;
            }

            /**
             * Gets the value of the effAvailableBalance property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEffAvailableBalance() {
                return effAvailableBalance;
            }

            /**
             * Sets the value of the effAvailableBalance property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEffAvailableBalance(String value) {
                this.effAvailableBalance = value;
            }

            /**
             * Gets the value of the fdBalance property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFdBalance() {
                return fdBalance;
            }

            /**
             * Sets the value of the fdBalance property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFdBalance(String value) {
                this.fdBalance = value;
            }

            /**
             * Gets the value of the clearBalance property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getClearBalance() {
                return clearBalance;
            }

            /**
             * Sets the value of the clearBalance property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setClearBalance(String value) {
                this.clearBalance = value;
            }

            /**
             * Gets the value of the unclearBalance property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUnclearBalance() {
                return unclearBalance;
            }

            /**
             * Sets the value of the unclearBalance property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUnclearBalance(String value) {
                this.unclearBalance = value;
            }

        }

    }

}
