//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.13 at 05:30:10 PM IST 
//


package com.cbs.ibl.pojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Transaction">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="TranType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="CustomerRefNum" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                   &lt;element name="DebitAccount" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="Amount" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="ValueDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="BenName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="BENE_ACNO" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="BENE_IFSC_CODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="BENE_BRANCH" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="BENE_BANK" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Bene_MobileNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Bene_EmailId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Bene_MMId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="MakerId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="CheckerId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Reserve1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Reserve2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Reserve3" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "transaction"
})
@XmlRootElement(name = "PaymentRequest")
public class PaymentRequest {

    @XmlElement(name = "Transaction", required = true)
    protected PaymentRequest.Transaction transaction;

    /**
     * Gets the value of the transaction property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentRequest.Transaction }
     *     
     */
    public PaymentRequest.Transaction getTransaction() {
        return transaction;
    }

    /**
     * Sets the value of the transaction property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentRequest.Transaction }
     *     
     */
    public void setTransaction(PaymentRequest.Transaction value) {
        this.transaction = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="TranType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="CustomerRefNum" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *         &lt;element name="DebitAccount" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="Amount" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="ValueDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="BenName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="BENE_ACNO" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="BENE_IFSC_CODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="BENE_BRANCH" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="BENE_BANK" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Bene_MobileNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Bene_EmailId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Bene_MMId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="MakerId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="CheckerId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Reserve1" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Reserve2" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Reserve3" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "tranType",
        "customerRefNum",
        "debitAccount",
        "amount",
        "valueDate",
        "benName",
        "beneacno",
        "beneifsccode",
        "benebranch",
        "benebank",
        "beneMobileNo",
        "beneEmailId",
        "beneMMId",
        "makerId",
        "checkerId",
        "reserve1",
        "reserve2",
        "reserve3"
    })
    public static class Transaction {

        @XmlElement(name = "TranType", required = true)
        protected String tranType;
        @XmlElement(name = "CustomerRefNum")
        protected String customerRefNum;
        @XmlElement(name = "DebitAccount")
        protected String debitAccount;
        @XmlElement(name = "Amount")
        protected String amount;
        @XmlElement(name = "ValueDate", required = true)
        protected String valueDate;
        @XmlElement(name = "BenName", required = true)
        protected String benName;
        @XmlElement(name = "BENE_ACNO")
        protected String beneacno;
        @XmlElement(name = "BENE_IFSC_CODE", required = true)
        protected String beneifsccode;
        @XmlElement(name = "BENE_BRANCH", required = true)
        protected String benebranch;
        @XmlElement(name = "BENE_BANK", required = true)
        protected String benebank;
        @XmlElement(name = "Bene_MobileNo", required = true)
        protected String beneMobileNo;
        @XmlElement(name = "Bene_EmailId", required = true)
        protected String beneEmailId;
        @XmlElement(name = "Bene_MMId", required = true)
        protected String beneMMId;
        @XmlElement(name = "MakerId", required = true)
        protected String makerId;
        @XmlElement(name = "CheckerId", required = true)
        protected String checkerId;
        @XmlElement(name = "Reserve1", required = true)
        protected String reserve1;
        @XmlElement(name = "Reserve2", required = true)
        protected String reserve2;
        @XmlElement(name = "Reserve3", required = true)
        protected String reserve3;

        /**
         * Gets the value of the tranType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTranType() {
            return tranType;
        }

        /**
         * Sets the value of the tranType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTranType(String value) {
            this.tranType = value;
        }

        /**
         * Gets the value of the customerRefNum property.
         * 
         */
        public String getCustomerRefNum() {
            return customerRefNum;
        }

        /**
         * Sets the value of the customerRefNum property.
         * 
         */
        public void setCustomerRefNum(String value) {
            this.customerRefNum = value;
        }

        /**
         * Gets the value of the debitAccount property.
         * 
         */
        public String getDebitAccount() {
            return debitAccount;
        }

        /**
         * Sets the value of the debitAccount property.
         * 
         */
        public void setDebitAccount(String value) {
            this.debitAccount = value;
        }

        /**
         * Gets the value of the amount property.
         * 
         */
        public String getAmount() {
            return amount;
        }

        /**
         * Sets the value of the amount property.
         * 
         */
        public void setAmount(String value) {
            this.amount = value;
        }

        /**
         * Gets the value of the valueDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValueDate() {
            return valueDate;
        }

        /**
         * Sets the value of the valueDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValueDate(String value) {
            this.valueDate = value;
        }

        /**
         * Gets the value of the benName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBenName() {
            return benName;
        }

        /**
         * Sets the value of the benName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBenName(String value) {
            this.benName = value;
        }

        /**
         * Gets the value of the beneacno property.
         * 
         */
        public String getBENEACNO() {
            return beneacno;
        }

        /**
         * Sets the value of the beneacno property.
         * 
         */
        public void setBENEACNO(String value) {
            this.beneacno = value;
        }

        /**
         * Gets the value of the beneifsccode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBENEIFSCCODE() {
            return beneifsccode;
        }

        /**
         * Sets the value of the beneifsccode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBENEIFSCCODE(String value) {
            this.beneifsccode = value;
        }

        /**
         * Gets the value of the benebranch property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBENEBRANCH() {
            return benebranch;
        }

        /**
         * Sets the value of the benebranch property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBENEBRANCH(String value) {
            this.benebranch = value;
        }

        /**
         * Gets the value of the benebank property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBENEBANK() {
            return benebank;
        }

        /**
         * Sets the value of the benebank property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBENEBANK(String value) {
            this.benebank = value;
        }

        /**
         * Gets the value of the beneMobileNo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBeneMobileNo() {
            return beneMobileNo;
        }

        /**
         * Sets the value of the beneMobileNo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBeneMobileNo(String value) {
            this.beneMobileNo = value;
        }

        /**
         * Gets the value of the beneEmailId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBeneEmailId() {
            return beneEmailId;
        }

        /**
         * Sets the value of the beneEmailId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBeneEmailId(String value) {
            this.beneEmailId = value;
        }

        /**
         * Gets the value of the beneMMId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBeneMMId() {
            return beneMMId;
        }

        /**
         * Sets the value of the beneMMId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBeneMMId(String value) {
            this.beneMMId = value;
        }

        /**
         * Gets the value of the makerId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMakerId() {
            return makerId;
        }

        /**
         * Sets the value of the makerId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMakerId(String value) {
            this.makerId = value;
        }

        /**
         * Gets the value of the checkerId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCheckerId() {
            return checkerId;
        }

        /**
         * Sets the value of the checkerId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCheckerId(String value) {
            this.checkerId = value;
        }

        /**
         * Gets the value of the reserve1 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getReserve1() {
            return reserve1;
        }

        /**
         * Sets the value of the reserve1 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setReserve1(String value) {
            this.reserve1 = value;
        }

        /**
         * Gets the value of the reserve2 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getReserve2() {
            return reserve2;
        }

        /**
         * Sets the value of the reserve2 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setReserve2(String value) {
            this.reserve2 = value;
        }

        /**
         * Gets the value of the reserve3 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getReserve3() {
            return reserve3;
        }

        /**
         * Sets the value of the reserve3 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setReserve3(String value) {
            this.reserve3 = value;
        }

    }

}
