//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.28 at 01:30:37 PM IST 
//


package com.cbs.ibl.pojo;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RespCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RespDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ReturnTrxn">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Transaction" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="CustRefNum" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="TrxnType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Amount" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ReferenceNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="CreditDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="TxnStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="EqErrorMessage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Remarks" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "respCode",
    "respDesc",
    "returnTrxn"
})
@XmlRootElement(name = "ReturnEnquiryResp")
public class ReturnEnquiryResp {

    @XmlElement(name = "RespCode", required = true)
    protected String respCode;
    @XmlElement(name = "RespDesc", required = true)
    protected String respDesc;
    @XmlElement(name = "ReturnTrxn", required = true)
    protected ReturnEnquiryResp.ReturnTrxn returnTrxn;

    /**
     * Gets the value of the respCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRespCode() {
        return respCode;
    }

    /**
     * Sets the value of the respCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRespCode(String value) {
        this.respCode = value;
    }

    /**
     * Gets the value of the respDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRespDesc() {
        return respDesc;
    }

    /**
     * Sets the value of the respDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRespDesc(String value) {
        this.respDesc = value;
    }

    /**
     * Gets the value of the returnTrxn property.
     * 
     * @return
     *     possible object is
     *     {@link ReturnEnquiryResp.ReturnTrxn }
     *     
     */
    public ReturnEnquiryResp.ReturnTrxn getReturnTrxn() {
        return returnTrxn;
    }

    /**
     * Sets the value of the returnTrxn property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReturnEnquiryResp.ReturnTrxn }
     *     
     */
    public void setReturnTrxn(ReturnEnquiryResp.ReturnTrxn value) {
        this.returnTrxn = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Transaction" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="CustRefNum" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="TrxnType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Amount" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ReferenceNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="CreditDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="TxnStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="EqErrorMessage" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Remarks" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "transaction"
    })
    public static class ReturnTrxn {

        @XmlElement(name = "Transaction")
        protected List<ReturnEnquiryResp.ReturnTrxn.Transaction> transaction;

        /**
         * Gets the value of the transaction property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the transaction property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTransaction().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ReturnEnquiryResp.ReturnTrxn.Transaction }
         * 
         * 
         */
        public List<ReturnEnquiryResp.ReturnTrxn.Transaction> getTransaction() {
            if (transaction == null) {
                transaction = new ArrayList<ReturnEnquiryResp.ReturnTrxn.Transaction>();
            }
            return this.transaction;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="CustRefNum" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="TrxnType" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Amount" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ReferenceNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="CreditDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="TxnStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="EqErrorMessage" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Remarks" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "custRefNum",
            "trxnType",
            "amount",
            "referenceNo",
            "creditDate",
            "txnStatus",
            "eqErrorMessage",
            "remarks"
        })
        public static class Transaction {

            @XmlElement(name = "CustRefNum", required = true)
            protected String custRefNum;
            @XmlElement(name = "TrxnType", required = true)
            protected String trxnType;
            @XmlElement(name = "Amount", required = true)
            protected String amount;
            @XmlElement(name = "ReferenceNo", required = true)
            protected String referenceNo;
            @XmlElement(name = "CreditDate", required = true)
            protected String creditDate;
            @XmlElement(name = "TxnStatus", required = true)
            protected String txnStatus;
            @XmlElement(name = "EqErrorMessage", required = true)
            protected String eqErrorMessage;
            @XmlElement(name = "Remarks", required = true)
            protected String remarks;

            /**
             * Gets the value of the custRefNum property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCustRefNum() {
                return custRefNum;
            }

            /**
             * Sets the value of the custRefNum property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCustRefNum(String value) {
                this.custRefNum = value;
            }

            /**
             * Gets the value of the trxnType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTrxnType() {
                return trxnType;
            }

            /**
             * Sets the value of the trxnType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTrxnType(String value) {
                this.trxnType = value;
            }

            /**
             * Gets the value of the amount property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAmount() {
                return amount;
            }

            /**
             * Sets the value of the amount property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAmount(String value) {
                this.amount = value;
            }

            /**
             * Gets the value of the referenceNo property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getReferenceNo() {
                return referenceNo;
            }

            /**
             * Sets the value of the referenceNo property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setReferenceNo(String value) {
                this.referenceNo = value;
            }

            /**
             * Gets the value of the creditDate property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCreditDate() {
                return creditDate;
            }

            /**
             * Sets the value of the creditDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCreditDate(String value) {
                this.creditDate = value;
            }

            /**
             * Gets the value of the txnStatus property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTxnStatus() {
                return txnStatus;
            }

            /**
             * Sets the value of the txnStatus property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTxnStatus(String value) {
                this.txnStatus = value;
            }

            /**
             * Gets the value of the eqErrorMessage property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEqErrorMessage() {
                return eqErrorMessage;
            }

            /**
             * Sets the value of the eqErrorMessage property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEqErrorMessage(String value) {
                this.eqErrorMessage = value;
            }

            /**
             * Gets the value of the remarks property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRemarks() {
                return remarks;
            }

            /**
             * Sets the value of the remarks property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRemarks(String value) {
                this.remarks = value;
            }

        }

    }

}
