//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.27 at 04:20:00 PM IST 
//


package com.cbs.pojo.cpsms.paymentrequest;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.cpsms.paymentrequest package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.cpsms.paymentrequest
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Payments }
     * 
     */
    public Payments createPayments() {
        return new Payments();
    }

    /**
     * Create an instance of {@link Payments.BatchDetails }
     * 
     */
    public Payments.BatchDetails createPaymentsBatchDetails() {
        return new Payments.BatchDetails();
    }

    /**
     * Create an instance of {@link Payments.BatchDetails.CreditAccounts }
     * 
     */
    public Payments.BatchDetails.CreditAccounts createPaymentsBatchDetailsCreditAccounts() {
        return new Payments.BatchDetails.CreditAccounts();
    }

    /**
     * Create an instance of {@link Payments.BatchDetails.CreditAccounts.CreditAccount }
     * 
     */
    public Payments.BatchDetails.CreditAccounts.CreditAccount createPaymentsBatchDetailsCreditAccountsCreditAccount() {
        return new Payments.BatchDetails.CreditAccounts.CreditAccount();
    }

    /**
     * Create an instance of {@link Payments.BatchDetails.DebitAccounts }
     * 
     */
    public Payments.BatchDetails.DebitAccounts createPaymentsBatchDetailsDebitAccounts() {
        return new Payments.BatchDetails.DebitAccounts();
    }

    /**
     * Create an instance of {@link Payments.BatchDetails.DebitAccounts.DebitAccount }
     * 
     */
    public Payments.BatchDetails.DebitAccounts.DebitAccount createPaymentsBatchDetailsDebitAccountsDebitAccount() {
        return new Payments.BatchDetails.DebitAccounts.DebitAccount();
    }

    /**
     * Create an instance of {@link Payments.BatchDetails.CreditAccounts.CreditAccount.RmtInf }
     * 
     */
    public Payments.BatchDetails.CreditAccounts.CreditAccount.RmtInf createPaymentsBatchDetailsCreditAccountsCreditAccountRmtInf() {
        return new Payments.BatchDetails.CreditAccounts.CreditAccount.RmtInf();
    }

    /**
     * Create an instance of {@link Payments.BatchDetails.DebitAccounts.DebitAccount.FileOrgtr }
     * 
     */
    public Payments.BatchDetails.DebitAccounts.DebitAccount.FileOrgtr createPaymentsBatchDetailsDebitAccountsDebitAccountFileOrgtr() {
        return new Payments.BatchDetails.DebitAccounts.DebitAccount.FileOrgtr();
    }

}
