//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.27 at 04:20:00 PM IST 
//
package com.cbs.pojo.cpsms.paymentrequest;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained
 * within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BatchDetails" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="DebitAccounts">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="DebitAccount" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="FileOrgtr">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="C7002" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                     &lt;attribute name="C2020" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="C4063" type="{http://www.w3.org/2001/XMLSchema}float" />
 *                                     &lt;attribute name="C3380" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                     &lt;attribute name="C5756" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="C6021" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="C6091" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="C5629" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="CreditAccounts">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="CreditAccount" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="RmtInf">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="C7495" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                     &lt;attribute name="C4038" type="{http://www.w3.org/2001/XMLSchema}float" />
 *                                     &lt;attribute name="C5569" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="C6061" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="UID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="BankIIN" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="C6081" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="C5565" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="CPSMSTranId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="PmtMtd" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="CorporateId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="CPSMSBatchNo" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="C3535" type="{http://www.w3.org/2001/XMLSchema}short" />
 *                 &lt;attribute name="C1106" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                 &lt;attribute name="CdtsInMsg" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                 &lt;attribute name="CdtAmtInMsg" type="{http://www.w3.org/2001/XMLSchema}float" />
 *                 &lt;attribute name="PgNb" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                 &lt;attribute name="LastPgInd" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="MessageId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="PaymentProduct" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Source" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Destination" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="BankCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="BankName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="RecordsCount" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "batchDetails"
})
@XmlRootElement(name = "Payments")
public class Payments {

    @XmlElement(name = "BatchDetails")
    protected List<Payments.BatchDetails> batchDetails;
    @XmlAttribute(name = "MessageId")
    protected String messageId;
    @XmlAttribute(name = "PaymentProduct")
    protected String paymentProduct;
    @XmlAttribute(name = "Source")
    protected String source;
    @XmlAttribute(name = "Destination")
    protected String destination;
    @XmlAttribute(name = "BankCode")
    protected String bankCode;
    @XmlAttribute(name = "BankName")
    protected String bankName;
    @XmlAttribute(name = "RecordsCount")
    protected Byte recordsCount;

    /**
     * Gets the value of the batchDetails property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the batchDetails property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBatchDetails().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Payments.BatchDetails }
     *
     *
     */
    public List<Payments.BatchDetails> getBatchDetails() {
        if (batchDetails == null) {
            batchDetails = new ArrayList<Payments.BatchDetails>();
        }
        return this.batchDetails;
    }

    /**
     * Gets the value of the messageId property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getMessageId() {
        return messageId;
    }

    /**
     * Sets the value of the messageId property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setMessageId(String value) {
        this.messageId = value;
    }

    /**
     * Gets the value of the paymentProduct property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getPaymentProduct() {
        return paymentProduct;
    }

    /**
     * Sets the value of the paymentProduct property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setPaymentProduct(String value) {
        this.paymentProduct = value;
    }

    /**
     * Gets the value of the source property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setSource(String value) {
        this.source = value;
    }

    /**
     * Gets the value of the destination property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getDestination() {
        return destination;
    }

    /**
     * Sets the value of the destination property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setDestination(String value) {
        this.destination = value;
    }

    /**
     * Gets the value of the bankCode property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getBankCode() {
        return bankCode;
    }

    /**
     * Sets the value of the bankCode property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setBankCode(String value) {
        this.bankCode = value;
    }

    /**
     * Gets the value of the bankName property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * Sets the value of the bankName property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setBankName(String value) {
        this.bankName = value;
    }

    /**
     * Gets the value of the recordsCount property.
     *
     * @return possible object is {@link Byte }
     *
     */
    public Byte getRecordsCount() {
        return recordsCount;
    }

    /**
     * Sets the value of the recordsCount property.
     *
     * @param value allowed object is {@link Byte }
     *
     */
    public void setRecordsCount(Byte value) {
        this.recordsCount = value;
    }

    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained
     * within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="DebitAccounts">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="DebitAccount" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="FileOrgtr">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="C7002" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                           &lt;attribute name="C2020" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="C4063" type="{http://www.w3.org/2001/XMLSchema}float" />
     *                           &lt;attribute name="C3380" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                           &lt;attribute name="C5756" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="C6021" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="C6091" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="C5629" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="CreditAccounts">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="CreditAccount" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="RmtInf">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="C7495" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                           &lt;attribute name="C4038" type="{http://www.w3.org/2001/XMLSchema}float" />
     *                           &lt;attribute name="C5569" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="C6061" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="UID" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="BankIIN" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="C6081" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="C5565" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="CPSMSTranId" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="PmtMtd" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="CorporateId" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="CPSMSBatchNo" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="C3535" type="{http://www.w3.org/2001/XMLSchema}short" />
     *       &lt;attribute name="C1106" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *       &lt;attribute name="CdtsInMsg" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *       &lt;attribute name="CdtAmtInMsg" type="{http://www.w3.org/2001/XMLSchema}float" />
     *       &lt;attribute name="PgNb" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *       &lt;attribute name="LastPgInd" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "debitAccounts",
        "creditAccounts"
    })
    public static class BatchDetails {

        @XmlElement(name = "DebitAccounts", required = true)
        protected Payments.BatchDetails.DebitAccounts debitAccounts;
        @XmlElement(name = "CreditAccounts", required = true)
        protected Payments.BatchDetails.CreditAccounts creditAccounts;
        @XmlAttribute(name = "CorporateId")
        protected String corporateId;
        @XmlAttribute(name = "CPSMSBatchNo")
        protected String cpsmsBatchNo;
        @XmlAttribute(name = "C3535")
        protected Short c3535;
        @XmlAttribute(name = "C1106")
        protected Byte c1106;
        @XmlAttribute(name = "CdtsInMsg")
        protected Byte cdtsInMsg;
        @XmlAttribute(name = "CdtAmtInMsg")
        protected Float cdtAmtInMsg;
        @XmlAttribute(name = "PgNb")
        protected Byte pgNb;
        @XmlAttribute(name = "LastPgInd")
        protected String lastPgInd;

        /**
         * Gets the value of the debitAccounts property.
         *
         * @return possible object is
         *     {@link Payments.BatchDetails.DebitAccounts }
         *
         */
        public Payments.BatchDetails.DebitAccounts getDebitAccounts() {
            return debitAccounts;
        }

        /**
         * Sets the value of the debitAccounts property.
         *
         * @param value allowed object is
         *     {@link Payments.BatchDetails.DebitAccounts }
         *
         */
        public void setDebitAccounts(Payments.BatchDetails.DebitAccounts value) {
            this.debitAccounts = value;
        }

        /**
         * Gets the value of the creditAccounts property.
         *
         * @return possible object is
         *     {@link Payments.BatchDetails.CreditAccounts }
         *
         */
        public Payments.BatchDetails.CreditAccounts getCreditAccounts() {
            return creditAccounts;
        }

        /**
         * Sets the value of the creditAccounts property.
         *
         * @param value allowed object is
         *     {@link Payments.BatchDetails.CreditAccounts }
         *
         */
        public void setCreditAccounts(Payments.BatchDetails.CreditAccounts value) {
            this.creditAccounts = value;
        }

        /**
         * Gets the value of the corporateId property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getCorporateId() {
            return corporateId;
        }

        /**
         * Sets the value of the corporateId property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setCorporateId(String value) {
            this.corporateId = value;
        }

        /**
         * Gets the value of the cpsmsBatchNo property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getCPSMSBatchNo() {
            return cpsmsBatchNo;
        }

        /**
         * Sets the value of the cpsmsBatchNo property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setCPSMSBatchNo(String value) {
            this.cpsmsBatchNo = value;
        }

        /**
         * Gets the value of the c3535 property.
         *
         * @return possible object is {@link Short }
         *
         */
        public Short getC3535() {
            return c3535;
        }

        /**
         * Sets the value of the c3535 property.
         *
         * @param value allowed object is {@link Short }
         *
         */
        public void setC3535(Short value) {
            this.c3535 = value;
        }

        /**
         * Gets the value of the c1106 property.
         *
         * @return possible object is {@link Byte }
         *
         */
        public Byte getC1106() {
            return c1106;
        }

        /**
         * Sets the value of the c1106 property.
         *
         * @param value allowed object is {@link Byte }
         *
         */
        public void setC1106(Byte value) {
            this.c1106 = value;
        }

        /**
         * Gets the value of the cdtsInMsg property.
         *
         * @return possible object is {@link Byte }
         *
         */
        public Byte getCdtsInMsg() {
            return cdtsInMsg;
        }

        /**
         * Sets the value of the cdtsInMsg property.
         *
         * @param value allowed object is {@link Byte }
         *
         */
        public void setCdtsInMsg(Byte value) {
            this.cdtsInMsg = value;
        }

        /**
         * Gets the value of the cdtAmtInMsg property.
         *
         * @return possible object is {@link Float }
         *
         */
        public Float getCdtAmtInMsg() {
            return cdtAmtInMsg;
        }

        /**
         * Sets the value of the cdtAmtInMsg property.
         *
         * @param value allowed object is {@link Float }
         *
         */
        public void setCdtAmtInMsg(Float value) {
            this.cdtAmtInMsg = value;
        }

        /**
         * Gets the value of the pgNb property.
         *
         * @return possible object is {@link Byte }
         *
         */
        public Byte getPgNb() {
            return pgNb;
        }

        /**
         * Sets the value of the pgNb property.
         *
         * @param value allowed object is {@link Byte }
         *
         */
        public void setPgNb(Byte value) {
            this.pgNb = value;
        }

        /**
         * Gets the value of the lastPgInd property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getLastPgInd() {
            return lastPgInd;
        }

        /**
         * Sets the value of the lastPgInd property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setLastPgInd(String value) {
            this.lastPgInd = value;
        }

        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content
         * contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="CreditAccount" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="RmtInf">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="C7495" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *                 &lt;attribute name="C4038" type="{http://www.w3.org/2001/XMLSchema}float" />
         *                 &lt;attribute name="C5569" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="C6061" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="UID" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="BankIIN" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="C6081" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="C5565" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="CPSMSTranId" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="PmtMtd" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "creditAccount"
        })
        public static class CreditAccounts {

            @XmlElement(name = "CreditAccount")
            protected List<Payments.BatchDetails.CreditAccounts.CreditAccount> creditAccount;

            /**
             * Gets the value of the creditAccount property.
             *
             * <p>
             * This accessor method returns a reference to the live list, not a
             * snapshot. Therefore any modification you make to the returned
             * list will be present inside the JAXB object. This is why there is
             * not a
             * <CODE>set</CODE> method for the creditAccount property.
             *
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getCreditAccount().add(newItem);
             * </pre>
             *
             *
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Payments.BatchDetails.CreditAccounts.CreditAccount }
             *
             *
             */
            public List<Payments.BatchDetails.CreditAccounts.CreditAccount> getCreditAccount() {
                if (creditAccount == null) {
                    creditAccount = new ArrayList<Payments.BatchDetails.CreditAccounts.CreditAccount>();
                }
                return this.creditAccount;
            }

            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected content
             * contained within this class.
             *
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="RmtInf">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="C7495" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *       &lt;attribute name="C4038" type="{http://www.w3.org/2001/XMLSchema}float" />
             *       &lt;attribute name="C5569" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="C6061" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="UID" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="BankIIN" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="C6081" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="C5565" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="CPSMSTranId" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="PmtMtd" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             *
             *
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "rmtInf"
            })
            public static class CreditAccount {

                @XmlElement(name = "RmtInf", required = true)
                protected Payments.BatchDetails.CreditAccounts.CreditAccount.RmtInf rmtInf;
                @XmlAttribute(name = "C4038")
                protected Float c4038;
                @XmlAttribute(name = "C5569")
                protected String c5569;
                @XmlAttribute(name = "C6061")
                protected String c6061;
                @XmlAttribute(name = "UID")
                protected String uid;
                @XmlAttribute(name = "BankIIN")
                protected String bankIIN;
                @XmlAttribute(name = "C6081")
                protected String c6081;
                @XmlAttribute(name = "C5565")
                protected String c5565;
                @XmlAttribute(name = "CPSMSTranId")
                protected String cpsmsTranId;
                @XmlAttribute(name = "PmtMtd")
                protected String pmtMtd;

                /**
                 * Gets the value of the rmtInf property.
                 *
                 * @return possible object is
                 *     {@link Payments.BatchDetails.CreditAccounts.CreditAccount.RmtInf }
                 *
                 */
                public Payments.BatchDetails.CreditAccounts.CreditAccount.RmtInf getRmtInf() {
                    return rmtInf;
                }

                /**
                 * Sets the value of the rmtInf property.
                 *
                 * @param value allowed object is
                 *     {@link Payments.BatchDetails.CreditAccounts.CreditAccount.RmtInf }
                 *
                 */
                public void setRmtInf(Payments.BatchDetails.CreditAccounts.CreditAccount.RmtInf value) {
                    this.rmtInf = value;
                }

                /**
                 * Gets the value of the c4038 property.
                 *
                 * @return possible object is {@link Float }
                 *
                 */
                public Float getC4038() {
                    return c4038;
                }

                /**
                 * Sets the value of the c4038 property.
                 *
                 * @param value allowed object is {@link Float }
                 *
                 */
                public void setC4038(Float value) {
                    this.c4038 = value;
                }

                /**
                 * Gets the value of the c5569 property.
                 *
                 * @return possible object is {@link String }
                 *
                 */
                public String getC5569() {
                    return c5569;
                }

                /**
                 * Sets the value of the c5569 property.
                 *
                 * @param value allowed object is {@link String }
                 *
                 */
                public void setC5569(String value) {
                    this.c5569 = value;
                }

                /**
                 * Gets the value of the c6061 property.
                 *
                 * @return possible object is {@link String }
                 *
                 */
                public String getC6061() {
                    return c6061;
                }

                /**
                 * Sets the value of the c6061 property.
                 *
                 * @param value allowed object is {@link String }
                 *
                 */
                public void setC6061(String value) {
                    this.c6061 = value;
                }

                /**
                 * Gets the value of the uid property.
                 *
                 * @return possible object is {@link String }
                 *
                 */
                public String getUID() {
                    return uid;
                }

                /**
                 * Sets the value of the uid property.
                 *
                 * @param value allowed object is {@link String }
                 *
                 */
                public void setUID(String value) {
                    this.uid = value;
                }

                /**
                 * Gets the value of the bankIIN property.
                 *
                 * @return possible object is {@link String }
                 *
                 */
                public String getBankIIN() {
                    return bankIIN;
                }

                /**
                 * Sets the value of the bankIIN property.
                 *
                 * @param value allowed object is {@link String }
                 *
                 */
                public void setBankIIN(String value) {
                    this.bankIIN = value;
                }

                /**
                 * Gets the value of the c6081 property.
                 *
                 * @return possible object is {@link String }
                 *
                 */
                public String getC6081() {
                    return c6081;
                }

                /**
                 * Sets the value of the c6081 property.
                 *
                 * @param value allowed object is {@link String }
                 *
                 */
                public void setC6081(String value) {
                    this.c6081 = value;
                }

                /**
                 * Gets the value of the c5565 property.
                 *
                 * @return possible object is {@link String }
                 *
                 */
                public String getC5565() {
                    return c5565;
                }

                /**
                 * Sets the value of the c5565 property.
                 *
                 * @param value allowed object is {@link String }
                 *
                 */
                public void setC5565(String value) {
                    this.c5565 = value;
                }

                /**
                 * Gets the value of the cpsmsTranId property.
                 *
                 * @return possible object is {@link String }
                 *
                 */
                public String getCPSMSTranId() {
                    return cpsmsTranId;
                }

                /**
                 * Sets the value of the cpsmsTranId property.
                 *
                 * @param value allowed object is {@link String }
                 *
                 */
                public void setCPSMSTranId(String value) {
                    this.cpsmsTranId = value;
                }

                /**
                 * Gets the value of the pmtMtd property.
                 *
                 * @return possible object is {@link String }
                 *
                 */
                public String getPmtMtd() {
                    return pmtMtd;
                }

                /**
                 * Sets the value of the pmtMtd property.
                 *
                 * @param value allowed object is {@link String }
                 *
                 */
                public void setPmtMtd(String value) {
                    this.pmtMtd = value;
                }

                /**
                 * <p>Java class for anonymous complex type.
                 *
                 * <p>The following schema fragment specifies the expected
                 * content contained within this class.
                 *
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="C7495" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 *
                 *
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "c7495"
                })
                public static class RmtInf {

                    @XmlElement(name = "C7495")
                    protected List<String> c7495;

                    /**
                     * Gets the value of the c7495 property.
                     *
                     * <p>
                     * This accessor method returns a reference to the live
                     * list, not a snapshot. Therefore any modification you make
                     * to the returned list will be present inside the JAXB
                     * object. This is why there is not a
                     * <CODE>set</CODE> method for the c7495 property.
                     *
                     * <p>
                     * For example, to add a new item, do as follows:
                     * <pre>
                     *    getC7495().add(newItem);
                     * </pre>
                     *
                     *
                     * <p>
                     * Objects of the following type(s) are allowed in the list
                     * {@link String }
                     *
                     *
                     */
                    public List<String> getC7495() {
                        if (c7495 == null) {
                            c7495 = new ArrayList<String>();
                        }
                        return this.c7495;
                    }
                }
            }
        }

        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content
         * contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="DebitAccount" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="FileOrgtr">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="C7002" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *                 &lt;attribute name="C2020" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="C4063" type="{http://www.w3.org/2001/XMLSchema}float" />
         *                 &lt;attribute name="C3380" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                 &lt;attribute name="C5756" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="C6021" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="C6091" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="C5629" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "debitAccount"
        })
        public static class DebitAccounts {

            @XmlElement(name = "DebitAccount")
            protected List<Payments.BatchDetails.DebitAccounts.DebitAccount> debitAccount;

            /**
             * Gets the value of the debitAccount property.
             *
             * <p>
             * This accessor method returns a reference to the live list, not a
             * snapshot. Therefore any modification you make to the returned
             * list will be present inside the JAXB object. This is why there is
             * not a
             * <CODE>set</CODE> method for the debitAccount property.
             *
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getDebitAccount().add(newItem);
             * </pre>
             *
             *
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Payments.BatchDetails.DebitAccounts.DebitAccount }
             *
             *
             */
            public List<Payments.BatchDetails.DebitAccounts.DebitAccount> getDebitAccount() {
                if (debitAccount == null) {
                    debitAccount = new ArrayList<Payments.BatchDetails.DebitAccounts.DebitAccount>();
                }
                return this.debitAccount;
            }

            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected content
             * contained within this class.
             *
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="FileOrgtr">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="C7002" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *       &lt;attribute name="C2020" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="C4063" type="{http://www.w3.org/2001/XMLSchema}float" />
             *       &lt;attribute name="C3380" type="{http://www.w3.org/2001/XMLSchema}int" />
             *       &lt;attribute name="C5756" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="C6021" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="C6091" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="C5629" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             *
             *
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "fileOrgtr"
            })
            public static class DebitAccount {

                @XmlElement(name = "FileOrgtr", required = true)
                protected Payments.BatchDetails.DebitAccounts.DebitAccount.FileOrgtr fileOrgtr;
                @XmlAttribute(name = "C2020")
                protected String c2020;
                @XmlAttribute(name = "C4063")
                protected Float c4063;
                @XmlAttribute(name = "C3380")
                protected Integer c3380;
                @XmlAttribute(name = "C5756")
                protected String c5756;
                @XmlAttribute(name = "C6021")
                protected String c6021;
                @XmlAttribute(name = "C6091")
                protected String c6091;
                @XmlAttribute(name = "C5629")
                protected String c5629;

                /**
                 * Gets the value of the fileOrgtr property.
                 *
                 * @return possible object is
                 *     {@link Payments.BatchDetails.DebitAccounts.DebitAccount.FileOrgtr }
                 *
                 */
                public Payments.BatchDetails.DebitAccounts.DebitAccount.FileOrgtr getFileOrgtr() {
                    return fileOrgtr;
                }

                /**
                 * Sets the value of the fileOrgtr property.
                 *
                 * @param value allowed object is
                 *     {@link Payments.BatchDetails.DebitAccounts.DebitAccount.FileOrgtr }
                 *
                 */
                public void setFileOrgtr(Payments.BatchDetails.DebitAccounts.DebitAccount.FileOrgtr value) {
                    this.fileOrgtr = value;
                }

                /**
                 * Gets the value of the c2020 property.
                 *
                 * @return possible object is {@link String }
                 *
                 */
                public String getC2020() {
                    return c2020;
                }

                /**
                 * Sets the value of the c2020 property.
                 *
                 * @param value allowed object is {@link String }
                 *
                 */
                public void setC2020(String value) {
                    this.c2020 = value;
                }

                /**
                 * Gets the value of the c4063 property.
                 *
                 * @return possible object is {@link Float }
                 *
                 */
                public Float getC4063() {
                    return c4063;
                }

                /**
                 * Sets the value of the c4063 property.
                 *
                 * @param value allowed object is {@link Float }
                 *
                 */
                public void setC4063(Float value) {
                    this.c4063 = value;
                }

                /**
                 * Gets the value of the c3380 property.
                 *
                 * @return possible object is {@link Integer }
                 *
                 */
                public Integer getC3380() {
                    return c3380;
                }

                /**
                 * Sets the value of the c3380 property.
                 *
                 * @param value allowed object is {@link Integer }
                 *
                 */
                public void setC3380(Integer value) {
                    this.c3380 = value;
                }

                /**
                 * Gets the value of the c5756 property.
                 *
                 * @return possible object is {@link String }
                 *
                 */
                public String getC5756() {
                    return c5756;
                }

                /**
                 * Sets the value of the c5756 property.
                 *
                 * @param value allowed object is {@link String }
                 *
                 */
                public void setC5756(String value) {
                    this.c5756 = value;
                }

                /**
                 * Gets the value of the c6021 property.
                 *
                 * @return possible object is {@link String }
                 *
                 */
                public String getC6021() {
                    return c6021;
                }

                /**
                 * Sets the value of the c6021 property.
                 *
                 * @param value allowed object is {@link String }
                 *
                 */
                public void setC6021(String value) {
                    this.c6021 = value;
                }

                /**
                 * Gets the value of the c6091 property.
                 *
                 * @return possible object is {@link String }
                 *
                 */
                public String getC6091() {
                    return c6091;
                }

                /**
                 * Sets the value of the c6091 property.
                 *
                 * @param value allowed object is {@link String }
                 *
                 */
                public void setC6091(String value) {
                    this.c6091 = value;
                }

                /**
                 * Gets the value of the c5629 property.
                 *
                 * @return possible object is {@link String }
                 *
                 */
                public String getC5629() {
                    return c5629;
                }

                /**
                 * Sets the value of the c5629 property.
                 *
                 * @param value allowed object is {@link String }
                 *
                 */
                public void setC5629(String value) {
                    this.c5629 = value;
                }

                /**
                 * <p>Java class for anonymous complex type.
                 *
                 * <p>The following schema fragment specifies the expected
                 * content contained within this class.
                 *
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="C7002" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 *
                 *
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "c7002"
                })
                public static class FileOrgtr {

                    @XmlElement(name = "C7002")
                    protected List<String> c7002;

                    /**
                     * Gets the value of the c7002 property.
                     *
                     * <p>
                     * This accessor method returns a reference to the live
                     * list, not a snapshot. Therefore any modification you make
                     * to the returned list will be present inside the JAXB
                     * object. This is why there is not a
                     * <CODE>set</CODE> method for the c7002 property.
                     *
                     * <p>
                     * For example, to add a new item, do as follows:
                     * <pre>
                     *    getC7002().add(newItem);
                     * </pre>
                     *
                     *
                     * <p>
                     * Objects of the following type(s) are allowed in the list
                     * {@link String }
                     *
                     *
                     */
                    public List<String> getC7002() {
                        if (c7002 == null) {
                            c7002 = new ArrayList<String>();
                        }
                        return this.c7002;
                    }
                }
            }
        }
    }
}
