//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.30 at 02:50:07 PM IST 
//
//package com.ncr.schemas.ecpix.pxf.filestructure._010001;
package com.cbs.dto.npci.cts;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the
 * com.ncr.schemas.ecpix.pxf.filestructure._010001 package.
 * <p>An ObjectFactory allows you to programatically construct new instances of
 * the Java representation for XML content. The Java representation of XML
 * content can consist of schema derived interfaces and classes representing the
 * binding of schema type definitions, element declarations and model groups.
 * Factory methods for each of these are provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {

    /**
     * Create a new ObjectFactory that can be used to create new instances of
     * schema derived classes for package:
     * com.ncr.schemas.ecpix.pxf.filestructure._010001
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FileHeader }
     *
     */
    public FileHeader createFileHeader() {
        return new FileHeader();
    }

    /**
     * Create an instance of {@link FileHeader.Item }
     *
     */
    public FileHeader.Item createFileHeaderItem() {
        return new FileHeader.Item();
    }

    /**
     * Create an instance of {@link FileHeader.Item.ImageViewDetail }
     *
     */
    public FileHeader.Item.ImageViewDetail createFileHeaderItemImageViewDetail() {
        return new FileHeader.Item.ImageViewDetail();
    }

    /**
     * Create an instance of {@link FileHeader.FileSummary }
     *
     */
    public FileHeader.FileSummary createFileHeaderFileSummary() {
        return new FileHeader.FileSummary();
    }

    /**
     * Create an instance of {@link FileHeader.Item.AddendA }
     *
     */
    public FileHeader.Item.AddendA createFileHeaderItemAddendA() {
        return new FileHeader.Item.AddendA();
    }

    /**
     * Create an instance of {@link FileHeader.Item.MICRDS }
     *
     */
    public FileHeader.Item.MICRDS createFileHeaderItemMICRDS() {
        return new FileHeader.Item.MICRDS();
    }

    /**
     * Create an instance of {@link FileHeader.Item.ImageViewDetail.ImageViewData
     * }
     *
     */
    public FileHeader.Item.ImageViewDetail.ImageViewData createFileHeaderItemImageViewDetailImageViewData() {
        return new FileHeader.Item.ImageViewDetail.ImageViewData();
    }

    /**
     * Create an instance of {@link FileHeader.Item.ImageViewDetail.ImageDS }
     *
     */
    public FileHeader.Item.ImageViewDetail.ImageDS createFileHeaderItemImageViewDetailImageDS() {
        return new FileHeader.Item.ImageViewDetail.ImageDS();
    }

    /**
     * Create an instance of {@link FileHeader.Item.ImageViewDetail.ImageViewAnalysis
     * }
     *
     */
    public FileHeader.Item.ImageViewDetail.ImageViewAnalysis createFileHeaderItemImageViewDetailImageViewAnalysis() {
        return new FileHeader.Item.ImageViewDetail.ImageViewAnalysis();
    }
}
