//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.16 at 02:21:07 PM IST 
//


package com.cbs.dto.npci.cts.ow.reverse;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ncr.schemas.ecpix.rf.filestructure._010001 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ncr.schemas.ecpix.rf.filestructure._010001
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FileHeader }
     * 
     */
    public FileHeader createFileHeader() {
        return new FileHeader();
    }

    /**
     * Create an instance of {@link FileHeader.Item }
     * 
     */
    public FileHeader.Item createFileHeaderItem() {
        return new FileHeader.Item();
    }

    /**
     * Create an instance of {@link FileHeader.FileSummary }
     * 
     */
    public FileHeader.FileSummary createFileHeaderFileSummary() {
        return new FileHeader.FileSummary();
    }

    /**
     * Create an instance of {@link FileHeader.Item.AddendA }
     * 
     */
    public FileHeader.Item.AddendA createFileHeaderItemAddendA() {
        return new FileHeader.Item.AddendA();
    }

}
