//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.21 at 04:57:20 PM IST 
//
package com.cbs.pojo.cpsms.initiatedpaymentdata;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained
 * within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BatchDetails">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="DebitTransactions">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Debit" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="C2006" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="C2020" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="C3501" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                                       &lt;element name="C4063" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                                       &lt;element name="C6346" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="C5756" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="C6021" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="C5185" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                           &lt;attribute name="C4063" type="{http://www.w3.org/2001/XMLSchema}float" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="CreditTransactions">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Credit" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="C2006" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="C5569" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="C6061" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="UID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="BankIIN" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="C2020" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="C3501" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                                       &lt;element name="C4038" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                                       &lt;element name="C6346" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="C3380" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                       &lt;element name="C3375" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                       &lt;element name="C3381" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="C5185" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="CPSMSBatchNo" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="MessageId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="PaymentProduct" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Source" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Destination" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="BankCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="BankName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="RecordsCount" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "batchDetails"
})
@XmlRootElement(name = "InitiatedPayments")
public class InitiatedPayments {

    @XmlElement(name = "BatchDetails", required = true)
    protected InitiatedPayments.BatchDetails batchDetails;
    @XmlAttribute(name = "MessageId")
    protected String messageId;
    @XmlAttribute(name = "PaymentProduct")
    protected String paymentProduct;
    @XmlAttribute(name = "Source")
    protected String source;
    @XmlAttribute(name = "Destination")
    protected String destination;
    @XmlAttribute(name = "BankCode")
    protected String bankCode;
    @XmlAttribute(name = "BankName")
    protected String bankName;
    @XmlAttribute(name = "RecordsCount")
    protected Byte recordsCount;

    /**
     * Gets the value of the batchDetails property.
     *
     * @return possible object is {@link InitiatedPayments.BatchDetails }
     *
     */
    public InitiatedPayments.BatchDetails getBatchDetails() {
        return batchDetails;
    }

    /**
     * Sets the value of the batchDetails property.
     *
     * @param value allowed object is {@link InitiatedPayments.BatchDetails }
     *
     */
    public void setBatchDetails(InitiatedPayments.BatchDetails value) {
        this.batchDetails = value;
    }

    /**
     * Gets the value of the messageId property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getMessageId() {
        return messageId;
    }

    /**
     * Sets the value of the messageId property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setMessageId(String value) {
        this.messageId = value;
    }

    /**
     * Gets the value of the paymentProduct property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getPaymentProduct() {
        return paymentProduct;
    }

    /**
     * Sets the value of the paymentProduct property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setPaymentProduct(String value) {
        this.paymentProduct = value;
    }

    /**
     * Gets the value of the source property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setSource(String value) {
        this.source = value;
    }

    /**
     * Gets the value of the destination property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getDestination() {
        return destination;
    }

    /**
     * Sets the value of the destination property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setDestination(String value) {
        this.destination = value;
    }

    /**
     * Gets the value of the bankCode property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getBankCode() {
        return bankCode;
    }

    /**
     * Sets the value of the bankCode property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setBankCode(String value) {
        this.bankCode = value;
    }

    /**
     * Gets the value of the bankName property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * Sets the value of the bankName property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setBankName(String value) {
        this.bankName = value;
    }

    /**
     * Gets the value of the recordsCount property.
     *
     * @return possible object is {@link Byte }
     *
     */
    public Byte getRecordsCount() {
        return recordsCount;
    }

    /**
     * Sets the value of the recordsCount property.
     *
     * @param value allowed object is {@link Byte }
     *
     */
    public void setRecordsCount(Byte value) {
        this.recordsCount = value;
    }

    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained
     * within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="DebitTransactions">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Debit" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="C2006" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="C2020" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="C3501" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                             &lt;element name="C4063" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                             &lt;element name="C6346" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="C5756" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="C6021" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="C5185" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *                 &lt;attribute name="C4063" type="{http://www.w3.org/2001/XMLSchema}float" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="CreditTransactions">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Credit" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="C2006" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="C5569" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="C6061" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="UID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="BankIIN" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="C2020" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="C3501" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                             &lt;element name="C4038" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                             &lt;element name="C6346" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="C3380" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                             &lt;element name="C3375" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                             &lt;element name="C3381" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="C5185" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="CPSMSBatchNo" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "debitTransactions",
        "creditTransactions"
    })
    public static class BatchDetails {

        @XmlElement(name = "DebitTransactions", required = true)
        protected InitiatedPayments.BatchDetails.DebitTransactions debitTransactions;
        @XmlElement(name = "CreditTransactions", required = true)
        protected InitiatedPayments.BatchDetails.CreditTransactions creditTransactions;
        @XmlAttribute(name = "CPSMSBatchNo")
        protected String cpsmsBatchNo;

        /**
         * Gets the value of the debitTransactions property.
         *
         * @return possible object is
         *     {@link InitiatedPayments.BatchDetails.DebitTransactions }
         *
         */
        public InitiatedPayments.BatchDetails.DebitTransactions getDebitTransactions() {
            return debitTransactions;
        }

        /**
         * Sets the value of the debitTransactions property.
         *
         * @param value allowed object is
         *     {@link InitiatedPayments.BatchDetails.DebitTransactions }
         *
         */
        public void setDebitTransactions(InitiatedPayments.BatchDetails.DebitTransactions value) {
            this.debitTransactions = value;
        }

        /**
         * Gets the value of the creditTransactions property.
         *
         * @return possible object is
         *     {@link InitiatedPayments.BatchDetails.CreditTransactions }
         *
         */
        public InitiatedPayments.BatchDetails.CreditTransactions getCreditTransactions() {
            return creditTransactions;
        }

        /**
         * Sets the value of the creditTransactions property.
         *
         * @param value allowed object is
         *     {@link InitiatedPayments.BatchDetails.CreditTransactions }
         *
         */
        public void setCreditTransactions(InitiatedPayments.BatchDetails.CreditTransactions value) {
            this.creditTransactions = value;
        }

        /**
         * Gets the value of the cpsmsBatchNo property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getCPSMSBatchNo() {
            return cpsmsBatchNo;
        }

        /**
         * Sets the value of the cpsmsBatchNo property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setCPSMSBatchNo(String value) {
            this.cpsmsBatchNo = value;
        }

        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content
         * contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Credit" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="C2006" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="C5569" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="C6061" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="UID" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="BankIIN" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="C2020" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="C3501" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *                   &lt;element name="C4038" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *                   &lt;element name="C6346" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="C3380" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                   &lt;element name="C3375" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                   &lt;element name="C3381" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="C5185" type="{http://www.w3.org/2001/XMLSchema}byte" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "credit"
        })
        public static class CreditTransactions {

            @XmlElement(name = "Credit")
            protected List<InitiatedPayments.BatchDetails.CreditTransactions.Credit> credit;
            @XmlAttribute(name = "C5185")
            //protected Byte c5185;
            protected Integer c5185;

            /**
             * Gets the value of the credit property.
             *
             * <p>
             * This accessor method returns a reference to the live list, not a
             * snapshot. Therefore any modification you make to the returned
             * list will be present inside the JAXB object. This is why there is
             * not a
             * <CODE>set</CODE> method for the credit property.
             *
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getCredit().add(newItem);
             * </pre>
             *
             *
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link InitiatedPayments.BatchDetails.CreditTransactions.Credit }
             *
             *
             */
            public List<InitiatedPayments.BatchDetails.CreditTransactions.Credit> getCredit() {
                if (credit == null) {
                    credit = new ArrayList<InitiatedPayments.BatchDetails.CreditTransactions.Credit>();
                }
                return this.credit;
            }

            /**
             * Gets the value of the c5185 property.
             *
             * @return possible object is {@link Byte }
             *
             */
            //            public Byte getC5185() {
            //                return c5185;
            //            }
            /**
             * Sets the value of the c5185 property.
             *
             * @param value allowed object is {@link Byte }
             *
             */
            //            public void setC5185(Byte value) {
            //                this.c5185 = value;
            //            }
            public Integer getC5185() {
                return c5185;
            }

            public void setC5185(Integer c5185) {
                this.c5185 = c5185;
            }

            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected content
             * contained within this class.
             *
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="C2006" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="C5569" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="C6061" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="UID" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="BankIIN" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="C2020" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="C3501" type="{http://www.w3.org/2001/XMLSchema}long"/>
             *         &lt;element name="C4038" type="{http://www.w3.org/2001/XMLSchema}float"/>
             *         &lt;element name="C6346" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="C3380" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *         &lt;element name="C3375" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *         &lt;element name="C3381" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             *
             *
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "c2006",
                "c5569",
                "c6061",
                "uid",
                "bankIIN",
                "c2020",
                "c3501",
                "c4038",
                "c6346",
                "c3380",
                "c3375",
                "c3381"
            })
            public static class Credit {

                @XmlElement(name = "C2006", required = true)
                protected String c2006;
                @XmlElement(name = "C5569", required = true)
                protected String c5569;
                @XmlElement(name = "C6061", required = true)
                protected String c6061;
                @XmlElement(name = "UID", required = true)
                protected String uid;
                @XmlElement(name = "BankIIN", required = true)
                protected String bankIIN;
                @XmlElement(name = "C2020", required = true)
                protected String c2020;
                @XmlElement(name = "C3501")
                protected long c3501;
                @XmlElement(name = "C4038")
                protected float c4038;
                @XmlElement(name = "C6346", required = true)
                protected String c6346;
                @XmlElement(name = "C3380")
                protected int c3380;
                @XmlElement(name = "C3375")
                protected int c3375;
                @XmlElement(name = "C3381")
                protected int c3381;

                /**
                 * Gets the value of the c2006 property.
                 *
                 * @return possible object is {@link String }
                 *
                 */
                public String getC2006() {
                    return c2006;
                }

                /**
                 * Sets the value of the c2006 property.
                 *
                 * @param value allowed object is {@link String }
                 *
                 */
                public void setC2006(String value) {
                    this.c2006 = value;
                }

                /**
                 * Gets the value of the c5569 property.
                 *
                 * @return possible object is {@link String }
                 *
                 */
                public String getC5569() {
                    return c5569;
                }

                /**
                 * Sets the value of the c5569 property.
                 *
                 * @param value allowed object is {@link String }
                 *
                 */
                public void setC5569(String value) {
                    this.c5569 = value;
                }

                /**
                 * Gets the value of the c6061 property.
                 *
                 * @return possible object is {@link String }
                 *
                 */
                public String getC6061() {
                    return c6061;
                }

                /**
                 * Sets the value of the c6061 property.
                 *
                 * @param value allowed object is {@link String }
                 *
                 */
                public void setC6061(String value) {
                    this.c6061 = value;
                }

                /**
                 * Gets the value of the uid property.
                 *
                 * @return possible object is {@link String }
                 *
                 */
                public String getUID() {
                    return uid;
                }

                /**
                 * Sets the value of the uid property.
                 *
                 * @param value allowed object is {@link String }
                 *
                 */
                public void setUID(String value) {
                    this.uid = value;
                }

                /**
                 * Gets the value of the bankIIN property.
                 *
                 * @return possible object is {@link String }
                 *
                 */
                public String getBankIIN() {
                    return bankIIN;
                }

                /**
                 * Sets the value of the bankIIN property.
                 *
                 * @param value allowed object is {@link String }
                 *
                 */
                public void setBankIIN(String value) {
                    this.bankIIN = value;
                }

                /**
                 * Gets the value of the c2020 property.
                 *
                 * @return possible object is {@link String }
                 *
                 */
                public String getC2020() {
                    return c2020;
                }

                /**
                 * Sets the value of the c2020 property.
                 *
                 * @param value allowed object is {@link String }
                 *
                 */
                public void setC2020(String value) {
                    this.c2020 = value;
                }

                /**
                 * Gets the value of the c3501 property.
                 *
                 */
                public long getC3501() {
                    return c3501;
                }

                /**
                 * Sets the value of the c3501 property.
                 *
                 */
                public void setC3501(long value) {
                    this.c3501 = value;
                }

                /**
                 * Gets the value of the c4038 property.
                 *
                 */
                public float getC4038() {
                    return c4038;
                }

                /**
                 * Sets the value of the c4038 property.
                 *
                 */
                public void setC4038(float value) {
                    this.c4038 = value;
                }

                /**
                 * Gets the value of the c6346 property.
                 *
                 * @return possible object is {@link String }
                 *
                 */
                public String getC6346() {
                    return c6346;
                }

                /**
                 * Sets the value of the c6346 property.
                 *
                 * @param value allowed object is {@link String }
                 *
                 */
                public void setC6346(String value) {
                    this.c6346 = value;
                }

                /**
                 * Gets the value of the c3380 property.
                 *
                 */
                public int getC3380() {
                    return c3380;
                }

                /**
                 * Sets the value of the c3380 property.
                 *
                 */
                public void setC3380(int value) {
                    this.c3380 = value;
                }

                /**
                 * Gets the value of the c3375 property.
                 *
                 */
                public int getC3375() {
                    return c3375;
                }

                /**
                 * Sets the value of the c3375 property.
                 *
                 */
                public void setC3375(int value) {
                    this.c3375 = value;
                }

                /**
                 * Gets the value of the c3381 property.
                 *
                 */
                public int getC3381() {
                    return c3381;
                }

                /**
                 * Sets the value of the c3381 property.
                 *
                 */
                public void setC3381(int value) {
                    this.c3381 = value;
                }
            }
        }

        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content
         * contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Debit" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="C2006" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="C2020" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="C3501" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *                   &lt;element name="C4063" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *                   &lt;element name="C6346" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="C5756" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="C6021" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="C5185" type="{http://www.w3.org/2001/XMLSchema}byte" />
         *       &lt;attribute name="C4063" type="{http://www.w3.org/2001/XMLSchema}float" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "debit"
        })
        public static class DebitTransactions {

            @XmlElement(name = "Debit")
            protected List<InitiatedPayments.BatchDetails.DebitTransactions.Debit> debit;
            @XmlAttribute(name = "C5756")
            protected String c5756;
            @XmlAttribute(name = "C6021")
            protected String c6021;
            @XmlAttribute(name = "C5185")
            protected Byte c5185;
            @XmlAttribute(name = "C4063")
            protected Float c4063;

            /**
             * Gets the value of the debit property.
             *
             * <p>
             * This accessor method returns a reference to the live list, not a
             * snapshot. Therefore any modification you make to the returned
             * list will be present inside the JAXB object. This is why there is
             * not a
             * <CODE>set</CODE> method for the debit property.
             *
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getDebit().add(newItem);
             * </pre>
             *
             *
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link InitiatedPayments.BatchDetails.DebitTransactions.Debit }
             *
             *
             */
            public List<InitiatedPayments.BatchDetails.DebitTransactions.Debit> getDebit() {
                if (debit == null) {
                    debit = new ArrayList<InitiatedPayments.BatchDetails.DebitTransactions.Debit>();
                }
                return this.debit;
            }

            /**
             * Gets the value of the c5756 property.
             *
             * @return possible object is {@link String }
             *
             */
            public String getC5756() {
                return c5756;
            }

            /**
             * Sets the value of the c5756 property.
             *
             * @param value allowed object is {@link String }
             *
             */
            public void setC5756(String value) {
                this.c5756 = value;
            }

            /**
             * Gets the value of the c6021 property.
             *
             * @return possible object is {@link String }
             *
             */
            public String getC6021() {
                return c6021;
            }

            /**
             * Sets the value of the c6021 property.
             *
             * @param value allowed object is {@link String }
             *
             */
            public void setC6021(String value) {
                this.c6021 = value;
            }

            /**
             * Gets the value of the c5185 property.
             *
             * @return possible object is {@link Byte }
             *
             */
            public Byte getC5185() {
                return c5185;
            }

            /**
             * Sets the value of the c5185 property.
             *
             * @param value allowed object is {@link Byte }
             *
             */
            public void setC5185(Byte value) {
                this.c5185 = value;
            }

            /**
             * Gets the value of the c4063 property.
             *
             * @return possible object is {@link Float }
             *
             */
            public Float getC4063() {
                return c4063;
            }

            /**
             * Sets the value of the c4063 property.
             *
             * @param value allowed object is {@link Float }
             *
             */
            public void setC4063(Float value) {
                this.c4063 = value;
            }

            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected content
             * contained within this class.
             *
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="C2006" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="C2020" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="C3501" type="{http://www.w3.org/2001/XMLSchema}long"/>
             *         &lt;element name="C4063" type="{http://www.w3.org/2001/XMLSchema}float"/>
             *         &lt;element name="C6346" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             *
             *
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "c2006",
                "c2020",
                "c3501",
                "c4063",
                "c6346"
            })
            public static class Debit {

                @XmlElement(name = "C2006", required = true)
                protected String c2006;
                @XmlElement(name = "C2020", required = true)
                protected String c2020;
                @XmlElement(name = "C3501")
                protected long c3501;
                @XmlElement(name = "C4063")
                protected float c4063;
                @XmlElement(name = "C6346", required = true)
                protected String c6346;

                /**
                 * Gets the value of the c2006 property.
                 *
                 * @return possible object is {@link String }
                 *
                 */
                public String getC2006() {
                    return c2006;
                }

                /**
                 * Sets the value of the c2006 property.
                 *
                 * @param value allowed object is {@link String }
                 *
                 */
                public void setC2006(String value) {
                    this.c2006 = value;
                }

                /**
                 * Gets the value of the c2020 property.
                 *
                 * @return possible object is {@link String }
                 *
                 */
                public String getC2020() {
                    return c2020;
                }

                /**
                 * Sets the value of the c2020 property.
                 *
                 * @param value allowed object is {@link String }
                 *
                 */
                public void setC2020(String value) {
                    this.c2020 = value;
                }

                /**
                 * Gets the value of the c3501 property.
                 *
                 */
                public long getC3501() {
                    return c3501;
                }

                /**
                 * Sets the value of the c3501 property.
                 *
                 */
                public void setC3501(long value) {
                    this.c3501 = value;
                }

                /**
                 * Gets the value of the c4063 property.
                 *
                 */
                public float getC4063() {
                    return c4063;
                }

                /**
                 * Sets the value of the c4063 property.
                 *
                 */
                public void setC4063(float value) {
                    this.c4063 = value;
                }

                /**
                 * Gets the value of the c6346 property.
                 *
                 * @return possible object is {@link String }
                 *
                 */
                public String getC6346() {
                    return c6346;
                }

                /**
                 * Sets the value of the c6346 property.
                 *
                 * @param value allowed object is {@link String }
                 *
                 */
                public void setC6346(String value) {
                    this.c6346 = value;
                }
            }
        }
    }
}
