//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.21 at 05:26:45 PM IST 
//
package com.cbs.pojo.mms.esign.pain011;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for Document complex type.
 *
 * <p>The following schema fragment specifies the expected content contained
 * within this class.
 *
 * <pre>
 * &lt;complexType name="Document">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MndtCxlReq" type="{urn:iso:std:iso:20022:tech:xsd:pain.011.001.04}MandateCancellationRequestV04"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Document", propOrder = {
    "mndtCxlReq"
})
public class Document {

    @XmlElement(name = "MndtCxlReq", required = true)
    protected MandateCancellationRequestV04 mndtCxlReq;

    /**
     * Gets the value of the mndtCxlReq property.
     *
     * @return possible object is {@link MandateCancellationRequestV04 }
     *
     */
    public MandateCancellationRequestV04 getMndtCxlReq() {
        return mndtCxlReq;
    }

    /**
     * Sets the value of the mndtCxlReq property.
     *
     * @param value allowed object is {@link MandateCancellationRequestV04 }
     *
     */
    public void setMndtCxlReq(MandateCancellationRequestV04 value) {
        this.mndtCxlReq = value;
    }
}
