//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.26 at 05:21:06 PM IST 
//


package com.cbs.pojo.mms.pain010;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MandateAmendmentRequestV01 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MandateAmendmentRequestV01">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="GrpHdr" type="{urn:iso:std:iso:20022:tech:xsd:pain.010.001.01}GroupHeader31"/>
 *         &lt;element name="UndrlygAmdmntDtls" type="{urn:iso:std:iso:20022:tech:xsd:pain.010.001.01}MandateAmendment1"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MandateAmendmentRequestV01", propOrder = {
    "grpHdr",
    "undrlygAmdmntDtls"
})
public class MandateAmendmentRequestV01 {

    @XmlElement(name = "GrpHdr", required = true)
    protected GroupHeader31 grpHdr;
    @XmlElement(name = "UndrlygAmdmntDtls", required = true)
    protected MandateAmendment1 undrlygAmdmntDtls;

    /**
     * Gets the value of the grpHdr property.
     * 
     * @return
     *     possible object is
     *     {@link GroupHeader31 }
     *     
     */
    public GroupHeader31 getGrpHdr() {
        return grpHdr;
    }

    /**
     * Sets the value of the grpHdr property.
     * 
     * @param value
     *     allowed object is
     *     {@link GroupHeader31 }
     *     
     */
    public void setGrpHdr(GroupHeader31 value) {
        this.grpHdr = value;
    }

    /**
     * Gets the value of the undrlygAmdmntDtls property.
     * 
     * @return
     *     possible object is
     *     {@link MandateAmendment1 }
     *     
     */
    public MandateAmendment1 getUndrlygAmdmntDtls() {
        return undrlygAmdmntDtls;
    }

    /**
     * Sets the value of the undrlygAmdmntDtls property.
     * 
     * @param value
     *     allowed object is
     *     {@link MandateAmendment1 }
     *     
     */
    public void setUndrlygAmdmntDtls(MandateAmendment1 value) {
        this.undrlygAmdmntDtls = value;
    }

}
