//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.10 at 07:04:01 PM IST 
//


package com.cbs.pojo.cpsms.transactionsdatarequest;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Account" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Transaction" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;choice maxOccurs="unbounded" minOccurs="0">
 *                             &lt;element name="Date" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ValueDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="TransactionType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="TransactionCategory" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ChannelType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="InstrumentNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="InstrumentDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Amount" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="PostTranBal" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Remarks" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="DrCrAccountNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="DrCrAccountName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="UniqueTransactionNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="TranRefNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="CPSMSTransactionId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Narratives">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Narration" maxOccurs="unbounded" minOccurs="0">
 *                                         &lt;complexType>
 *                                           &lt;simpleContent>
 *                                             &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                               &lt;attribute name="SrNo" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                               &lt;attribute name="Text" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                             &lt;/extension>
 *                                           &lt;/simpleContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/choice>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="AccountNo" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="BSRCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="MICRCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="OpeningBalance" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="ShadowOpeningBalance" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="ClosingBalance" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="ShadowClosingBalance" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="OpeningBalanceDate" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="ClosingBalanceDate" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="TransactionsCount" type="{http://www.w3.org/2001/XMLSchema}int" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="MessageId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Source" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Destination" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="BankCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="BankName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="RecordsCount" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "account"
})
@XmlRootElement(name = "TransactionDetails")
public class TransactionDetails {

    @XmlElement(name = "Account")
    protected List<TransactionDetails.Account> account;
    @XmlAttribute(name = "MessageId")
    protected String messageId;
    @XmlAttribute(name = "Source")
    protected String source;
    @XmlAttribute(name = "Destination")
    protected String destination;
    @XmlAttribute(name = "BankCode")
    protected String bankCode;
    @XmlAttribute(name = "BankName")
    protected String bankName;
    @XmlAttribute(name = "RecordsCount")
    protected Integer recordsCount;    

    /**
     * Gets the value of the account property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the account property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAccount().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TransactionDetails.Account }
     * 
     * 
     */
    public List<TransactionDetails.Account> getAccount() {
        if (account == null) {
            account = new ArrayList<TransactionDetails.Account>();
        }
        return this.account;
    }

    /**
     * Gets the value of the messageId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageId() {
        return messageId;
    }

    /**
     * Sets the value of the messageId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageId(String value) {
        this.messageId = value;
    }

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSource(String value) {
        this.source = value;
    }

    /**
     * Gets the value of the destination property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestination() {
        return destination;
    }

    /**
     * Sets the value of the destination property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestination(String value) {
        this.destination = value;
    }

    /**
     * Gets the value of the bankCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBankCode() {
        return bankCode;
    }

    /**
     * Sets the value of the bankCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBankCode(String value) {
        this.bankCode = value;
    }

    /**
     * Gets the value of the bankName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * Sets the value of the bankName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBankName(String value) {
        this.bankName = value;
    }

    /**
     * Gets the value of the recordsCount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRecordsCount() {
        return recordsCount;
    }

    /**
     * Sets the value of the recordsCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRecordsCount(Integer value) {
        this.recordsCount = value;
    }   

    

    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Transaction" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;choice maxOccurs="unbounded" minOccurs="0">
     *                   &lt;element name="Date" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ValueDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="TransactionType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="TransactionCategory" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ChannelType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="InstrumentNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="InstrumentDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Amount" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="PostTranBal" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Remarks" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="DrCrAccountNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="DrCrAccountName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="UniqueTransactionNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="TranRefNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="CPSMSTransactionId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Narratives">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Narration" maxOccurs="unbounded" minOccurs="0">
     *                               &lt;complexType>
     *                                 &lt;simpleContent>
     *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                                     &lt;attribute name="SrNo" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                                     &lt;attribute name="Text" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                   &lt;/extension>
     *                                 &lt;/simpleContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/choice>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="AccountNo" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="BSRCode" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="MICRCode" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="OpeningBalance" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="ShadowOpeningBalance" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="ClosingBalance" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="ShadowClosingBalance" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="OpeningBalanceDate" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="ClosingBalanceDate" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="TransactionsCount" type="{http://www.w3.org/2001/XMLSchema}int" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "transaction"
    })
    public static class Account {

        @XmlElement(name = "Transaction")
        protected List<TransactionDetails.Account.Transaction> transaction;
        @XmlAttribute(name = "AccountNo")
        protected String accountNo;
        @XmlAttribute(name = "BSRCode")
        protected String bsrCode;
        @XmlAttribute(name = "MICRCode")
        protected String micrCode;
        @XmlAttribute(name = "OpeningBalance")
        protected String openingBalance;
        @XmlAttribute(name = "ShadowOpeningBalance")
        protected String shadowOpeningBalance;
        @XmlAttribute(name = "ClosingBalance")
        protected String closingBalance;
        @XmlAttribute(name = "ShadowClosingBalance")
        protected String shadowClosingBalance;
        @XmlAttribute(name = "OpeningBalanceDate")
        protected String openingBalanceDate;
        @XmlAttribute(name = "ClosingBalanceDate")
        protected String closingBalanceDate;
        @XmlAttribute(name = "TransactionsCount")
        protected Integer transactionsCount;

        /**
         * Gets the value of the transaction property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the transaction property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTransaction().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TransactionDetails.Account.Transaction }
         * 
         * 
         */
        public List<TransactionDetails.Account.Transaction> getTransaction() {
            if (transaction == null) {
                transaction = new ArrayList<TransactionDetails.Account.Transaction>();
            }
            return this.transaction;
        }

        /**
         * Gets the value of the accountNo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAccountNo() {
            return accountNo;
        }

        /**
         * Sets the value of the accountNo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAccountNo(String value) {
            this.accountNo = value;
        }

        /**
         * Gets the value of the bsrCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBSRCode() {
            return bsrCode;
        }

        /**
         * Sets the value of the bsrCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBSRCode(String value) {
            this.bsrCode = value;
        }

        /**
         * Gets the value of the micrCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMICRCode() {
            return micrCode;
        }

        /**
         * Sets the value of the micrCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMICRCode(String value) {
            this.micrCode = value;
        }

        /**
         * Gets the value of the openingBalance property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOpeningBalance() {
            return openingBalance;
        }

        /**
         * Sets the value of the openingBalance property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOpeningBalance(String value) {
            this.openingBalance = value;
        }

        /**
         * Gets the value of the shadowOpeningBalance property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getShadowOpeningBalance() {
            return shadowOpeningBalance;
        }

        /**
         * Sets the value of the shadowOpeningBalance property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setShadowOpeningBalance(String value) {
            this.shadowOpeningBalance = value;
        }

        /**
         * Gets the value of the closingBalance property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getClosingBalance() {
            return closingBalance;
        }

        /**
         * Sets the value of the closingBalance property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setClosingBalance(String value) {
            this.closingBalance = value;
        }

        /**
         * Gets the value of the shadowClosingBalance property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getShadowClosingBalance() {
            return shadowClosingBalance;
        }

        /**
         * Sets the value of the shadowClosingBalance property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setShadowClosingBalance(String value) {
            this.shadowClosingBalance = value;
        }

        /**
         * Gets the value of the openingBalanceDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOpeningBalanceDate() {
            return openingBalanceDate;
        }

        /**
         * Sets the value of the openingBalanceDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOpeningBalanceDate(String value) {
            this.openingBalanceDate = value;
        }

        /**
         * Gets the value of the closingBalanceDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getClosingBalanceDate() {
            return closingBalanceDate;
        }

        /**
         * Sets the value of the closingBalanceDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setClosingBalanceDate(String value) {
            this.closingBalanceDate = value;
        }

        /**
         * Gets the value of the transactionsCount property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getTransactionsCount() {
            return transactionsCount;
        }

        /**
         * Sets the value of the transactionsCount property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setTransactionsCount(Integer value) {
            this.transactionsCount = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;choice maxOccurs="unbounded" minOccurs="0">
         *         &lt;element name="Date" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ValueDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="TransactionType" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="TransactionCategory" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ChannelType" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="InstrumentNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="InstrumentDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Amount" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="PostTranBal" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Remarks" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="DrCrAccountNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="DrCrAccountName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="UniqueTransactionNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="TranRefNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="CPSMSTransactionId" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Narratives">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Narration" maxOccurs="unbounded" minOccurs="0">
         *                     &lt;complexType>
         *                       &lt;simpleContent>
         *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                           &lt;attribute name="SrNo" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                           &lt;attribute name="Text" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                         &lt;/extension>
         *                       &lt;/simpleContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/choice>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "dateOrValueDateOrTransactionType"
        })
        public static class Transaction {

            @XmlElementRefs({
                @XmlElementRef(name = "ChannelType", namespace = "http://cpsms.com/TransactionsDataRequest", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "Remarks", namespace = "http://cpsms.com/TransactionsDataRequest", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "DrCrAccountNumber", namespace = "http://cpsms.com/TransactionsDataRequest", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "DrCrAccountName", namespace = "http://cpsms.com/TransactionsDataRequest", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "DrCrBnkNm", namespace = "http://cpsms.com/TransactionsDataRequest", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "DrCrBnkBrCd", namespace = "http://cpsms.com/TransactionsDataRequest", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "UniqueTransactionNumber", namespace = "http://cpsms.com/TransactionsDataRequest", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "PostTranBal", namespace = "http://cpsms.com/TransactionsDataRequest", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "TranRefNo", namespace = "http://cpsms.com/TransactionsDataRequest", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "Date", namespace = "http://cpsms.com/TransactionsDataRequest", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "Narratives", namespace = "http://cpsms.com/TransactionsDataRequest", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "TransactionType", namespace = "http://cpsms.com/TransactionsDataRequest", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "TransactionCategory", namespace = "http://cpsms.com/TransactionsDataRequest", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "Amount", namespace = "http://cpsms.com/TransactionsDataRequest", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "CPSMSTransactionId", namespace = "http://cpsms.com/TransactionsDataRequest", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "InstrumentNo", namespace = "http://cpsms.com/TransactionsDataRequest", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "ValueDate", namespace = "http://cpsms.com/TransactionsDataRequest", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "InstrumentDate", namespace = "http://cpsms.com/TransactionsDataRequest", type = JAXBElement.class, required = false)
            })
            protected List<JAXBElement<?>> dateOrValueDateOrTransactionType;

            /**
             * Gets the value of the dateOrValueDateOrTransactionType property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the dateOrValueDateOrTransactionType property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getDateOrValueDateOrTransactionType().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link JAXBElement }{@code <}{@link String }{@code >}
             * {@link JAXBElement }{@code <}{@link String }{@code >}
             * {@link JAXBElement }{@code <}{@link String }{@code >}
             * {@link JAXBElement }{@code <}{@link String }{@code >}
             * {@link JAXBElement }{@code <}{@link String }{@code >}
             * {@link JAXBElement }{@code <}{@link String }{@code >}
             * {@link JAXBElement }{@code <}{@link String }{@code >}
             * {@link JAXBElement }{@code <}{@link String }{@code >}
             * {@link JAXBElement }{@code <}{@link TransactionDetails.Account.Transaction.Narratives }{@code >}
             * {@link JAXBElement }{@code <}{@link String }{@code >}
             * {@link JAXBElement }{@code <}{@link String }{@code >}
             * {@link JAXBElement }{@code <}{@link String }{@code >}
             * {@link JAXBElement }{@code <}{@link String }{@code >}
             * {@link JAXBElement }{@code <}{@link String }{@code >}
             * {@link JAXBElement }{@code <}{@link String }{@code >}
             * {@link JAXBElement }{@code <}{@link String }{@code >}
             * 
             * 
             */
            public List<JAXBElement<?>> getDateOrValueDateOrTransactionType() {
                if (dateOrValueDateOrTransactionType == null) {
                    dateOrValueDateOrTransactionType = new ArrayList<JAXBElement<?>>();
                }
                return this.dateOrValueDateOrTransactionType;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Narration" maxOccurs="unbounded" minOccurs="0">
             *           &lt;complexType>
             *             &lt;simpleContent>
             *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *                 &lt;attribute name="SrNo" type="{http://www.w3.org/2001/XMLSchema}int" />
             *                 &lt;attribute name="Text" type="{http://www.w3.org/2001/XMLSchema}string" />
             *               &lt;/extension>
             *             &lt;/simpleContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "narration"
            })
            public static class Narratives {

                @XmlElement(name = "Narration")
                protected List<TransactionDetails.Account.Transaction.Narratives.Narration> narration;

                /**
                 * Gets the value of the narration property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the narration property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getNarration().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link TransactionDetails.Account.Transaction.Narratives.Narration }
                 * 
                 * 
                 */
                public List<TransactionDetails.Account.Transaction.Narratives.Narration> getNarration() {
                    if (narration == null) {
                        narration = new ArrayList<TransactionDetails.Account.Transaction.Narratives.Narration>();
                    }
                    return this.narration;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;simpleContent>
                 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
                 *       &lt;attribute name="SrNo" type="{http://www.w3.org/2001/XMLSchema}int" />
                 *       &lt;attribute name="Text" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *     &lt;/extension>
                 *   &lt;/simpleContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "value"
                })
                public static class Narration {

                    @XmlValue
                    protected String value;
                    @XmlAttribute(name = "SrNo")
                    protected Integer srNo;
                    @XmlAttribute(name = "Text")
                    protected String text;

                    /**
                     * Gets the value of the value property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getValue() {
                        return value;
                    }

                    /**
                     * Sets the value of the value property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setValue(String value) {
                        this.value = value;
                    }

                    /**
                     * Gets the value of the srNo property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Integer }
                     *     
                     */
                    public Integer getSrNo() {
                        return srNo;
                    }

                    /**
                     * Sets the value of the srNo property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Integer }
                     *     
                     */
                    public void setSrNo(Integer value) {
                        this.srNo = value;
                    }

                    /**
                     * Gets the value of the text property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getText() {
                        return text;
                    }

                    /**
                     * Sets the value of the text property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setText(String value) {
                        this.text = value;
                    }

                }

            }

        }

    }

}
