//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.09 at 11:59:51 AM IST 
//
package com.cbs.dto.npci.cts.reverse;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;

/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained
 * within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Item" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="AddendA">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="BOFDRoutNo" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="BOFDBusDate" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="DepositorAcct" type="{http://www.w3.org/2001/XMLSchema}long" />
 *                           &lt;attribute name="IFSC" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="ItemSeqNo" type="{http://www.w3.org/2001/XMLSchema}long" />
 *                 &lt;attribute name="PayorBankRoutNo" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="Amount" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="SerialNo" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="TransCode" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                 &lt;attribute name="PresentingBankRoutNo" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="PresentmentDate" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="CycleNo" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                 &lt;attribute name="ClearingType" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                 &lt;attribute name="ReturnReason" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                 &lt;attribute name="ReturnReasonComment" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="FileSummary">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="TotalItemCount" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                 &lt;attribute name="TotalAmount" type="{http://www.w3.org/2001/XMLSchema}int" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="VersionNumber" type="{http://www.w3.org/2001/XMLSchema}short" />
 *       &lt;attribute name="TestFileIndicator" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="CreationDate" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="CreationTime" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="FileID" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "item",
    "fileSummary"
})
@XmlRootElement(name = "FileHeader")
public class FileHeader {

    @XmlElement(name = "Item")
    protected List<FileHeader.Item> item;
    @XmlElement(name = "FileSummary", required = true)
    protected FileHeader.FileSummary fileSummary;
    @XmlAttribute(name = "VersionNumber")
    protected String versionNumber;
    @XmlAttribute(name = "TestFileIndicator")
    protected String testFileIndicator;
    @XmlAttribute(name = "CreationDate")
    protected String creationDate;
    @XmlAttribute(name = "CreationTime")
    protected String creationTime;
    @XmlAttribute(name = "FileID")
    protected String fileID;

    /**
     * Gets the value of the item property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the item property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItem().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FileHeader.Item }
     *
     *
     */
    public List<FileHeader.Item> getItem() {
        if (item == null) {
            item = new ArrayList<FileHeader.Item>();
        }
        return this.item;
    }

    /**
     * Gets the value of the fileSummary property.
     *
     * @return possible object is {@link FileHeader.FileSummary }
     *
     */
    public FileHeader.FileSummary getFileSummary() {
        return fileSummary;
    }

    /**
     * Sets the value of the fileSummary property.
     *
     * @param value allowed object is {@link FileHeader.FileSummary }
     *
     */
    public void setFileSummary(FileHeader.FileSummary value) {
        this.fileSummary = value;
    }

    /**
     * Gets the value of the versionNumber property.
     *
     * @return possible object is {@link Short }
     *
     */
    public String getVersionNumber() {
        return versionNumber;
    }

    /**
     * Sets the value of the versionNumber property.
     *
     * @param value allowed object is {@link Short }
     *
     */
    public void setVersionNumber(String value) {
        this.versionNumber = value;
    }

    /**
     * Gets the value of the testFileIndicator property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getTestFileIndicator() {
        return testFileIndicator;
    }

    /**
     * Sets the value of the testFileIndicator property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setTestFileIndicator(String value) {
        this.testFileIndicator = value;
    }

    /**
     * Gets the value of the creationDate property.
     *
     * @return possible object is {@link Integer }
     *
     */
    public String getCreationDate() {
        return creationDate;
    }

    /**
     * Sets the value of the creationDate property.
     *
     * @param value allowed object is {@link Integer }
     *
     */
    public void setCreationDate(String value) {
        this.creationDate = value;
    }

    /**
     * Gets the value of the creationTime property.
     *
     * @return possible object is {@link Integer }
     *
     */
    public String getCreationTime() {
        return creationTime;
    }

    /**
     * Sets the value of the creationTime property.
     *
     * @param value allowed object is {@link Integer }
     *
     */
    public void setCreationTime(String value) {
        this.creationTime = value;
    }

    /**
     * Gets the value of the fileID property.
     *
     * @return possible object is {@link Byte }
     *
     */
    public String getFileID() {
        return fileID;
    }

    /**
     * Sets the value of the fileID property.
     *
     * @param value allowed object is {@link Byte }
     *
     */
    public void setFileID(String value) {
        this.fileID = value;
    }

    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained
     * within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="TotalItemCount" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *       &lt;attribute name="TotalAmount" type="{http://www.w3.org/2001/XMLSchema}int" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class FileSummary {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "TotalItemCount")
        protected String totalItemCount;
        @XmlAttribute(name = "TotalAmount")
        protected String totalAmount;

        /**
         * Gets the value of the value property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the totalItemCount property.
         *
         * @return possible object is {@link Byte }
         *
         */
        public String getTotalItemCount() {
            return totalItemCount;
        }

        /**
         * Sets the value of the totalItemCount property.
         *
         * @param value allowed object is {@link Byte }
         *
         */
        public void setTotalItemCount(String value) {
            this.totalItemCount = value;
        }

        /**
         * Gets the value of the totalAmount property.
         *
         * @return possible object is {@link Integer }
         *
         */
        public String getTotalAmount() {
            return totalAmount;
        }

        /**
         * Sets the value of the totalAmount property.
         *
         * @param value allowed object is {@link Integer }
         *
         */
        public void setTotalAmount(String value) {
            this.totalAmount = value;
        }
    }

    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained
     * within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="AddendA">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="BOFDRoutNo" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="BOFDBusDate" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="DepositorAcct" type="{http://www.w3.org/2001/XMLSchema}long" />
     *                 &lt;attribute name="IFSC" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="ItemSeqNo" type="{http://www.w3.org/2001/XMLSchema}long" />
     *       &lt;attribute name="PayorBankRoutNo" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="Amount" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="SerialNo" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="TransCode" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *       &lt;attribute name="PresentingBankRoutNo" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="PresentmentDate" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="CycleNo" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *       &lt;attribute name="ClearingType" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *       &lt;attribute name="ReturnReason" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *       &lt;attribute name="ReturnReasonComment" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "addendA"
    })
    public static class Item {

        @XmlElement(name = "AddendA", required = true)
        protected FileHeader.Item.AddendA addendA;
        @XmlAttribute(name = "ItemSeqNo")
        protected String itemSeqNo;
        @XmlAttribute(name = "PayorBankRoutNo")
        protected String payorBankRoutNo;
        @XmlAttribute(name = "Amount")
        protected String amount;
        @XmlAttribute(name = "SerialNo")
        protected String serialNo;
        @XmlAttribute(name = "TransCode")
        protected String transCode;
        @XmlAttribute(name = "PresentingBankRoutNo")
        protected String presentingBankRoutNo;
        @XmlAttribute(name = "PresentmentDate")
        protected String presentmentDate;
        @XmlAttribute(name = "CycleNo")
        protected String cycleNo;
        @XmlAttribute(name = "ClearingType")
        protected String clearingType;
        @XmlAttribute(name = "ReturnReason")
        protected String returnReason;
        @XmlAttribute(name = "ReturnReasonComment")
        protected String returnReasonComment;

        /**
         * Gets the value of the addendA property.
         *
         * @return possible object is {@link FileHeader.Item.AddendA }
         *
         */
        public FileHeader.Item.AddendA getAddendA() {
            return addendA;
        }

        /**
         * Sets the value of the addendA property.
         *
         * @param value allowed object is {@link FileHeader.Item.AddendA }
         *
         */
        public void setAddendA(FileHeader.Item.AddendA value) {
            this.addendA = value;
        }

        /**
         * Gets the value of the itemSeqNo property.
         *
         * @return possible object is {@link Long }
         *
         */
        public String getItemSeqNo() {
            return itemSeqNo;
        }

        /**
         * Sets the value of the itemSeqNo property.
         *
         * @param value allowed object is {@link Long }
         *
         */
        public void setItemSeqNo(String value) {
            this.itemSeqNo = value;
        }

        /**
         * Gets the value of the payorBankRoutNo property.
         *
         * @return possible object is {@link Integer }
         *
         */
        public String getPayorBankRoutNo() {
            return payorBankRoutNo;
        }

        /**
         * Sets the value of the payorBankRoutNo property.
         *
         * @param value allowed object is {@link Integer }
         *
         */
        public void setPayorBankRoutNo(String value) {
            this.payorBankRoutNo = value;
        }

        /**
         * Gets the value of the amount property.
         *
         * @return possible object is {@link Integer }
         *
         */
        public String getAmount() {
            return amount;
        }

        /**
         * Sets the value of the amount property.
         *
         * @param value allowed object is {@link Integer }
         *
         */
        public void setAmount(String value) {
            this.amount = value;
        }

        /**
         * Gets the value of the serialNo property.
         *
         * @return possible object is {@link Integer }
         *
         */
        public String getSerialNo() {
            return serialNo;
        }

        /**
         * Sets the value of the serialNo property.
         *
         * @param value allowed object is {@link Integer }
         *
         */
        public void setSerialNo(String value) {
            this.serialNo = value;
        }

        /**
         * Gets the value of the transCode property.
         *
         * @return possible object is {@link Byte }
         *
         */
        public String getTransCode() {
            return transCode;
        }

        /**
         * Sets the value of the transCode property.
         *
         * @param value allowed object is {@link Byte }
         *
         */
        public void setTransCode(String value) {
            this.transCode = value;
        }

        /**
         * Gets the value of the presentingBankRoutNo property.
         *
         * @return possible object is {@link Integer }
         *
         */
        public String getPresentingBankRoutNo() {
            return presentingBankRoutNo;
        }

        /**
         * Sets the value of the presentingBankRoutNo property.
         *
         * @param value allowed object is {@link Integer }
         *
         */
        public void setPresentingBankRoutNo(String value) {
            this.presentingBankRoutNo = value;
        }

        /**
         * Gets the value of the presentmentDate property.
         *
         * @return possible object is {@link Integer }
         *
         */
        public String getPresentmentDate() {
            return presentmentDate;
        }

        /**
         * Sets the value of the presentmentDate property.
         *
         * @param value allowed object is {@link Integer }
         *
         */
        public void setPresentmentDate(String value) {
            this.presentmentDate = value;
        }

        /**
         * Gets the value of the cycleNo property.
         *
         * @return possible object is {@link Byte }
         *
         */
        public String getCycleNo() {
            return cycleNo;
        }

        /**
         * Sets the value of the cycleNo property.
         *
         * @param value allowed object is {@link Byte }
         *
         */
        public void setCycleNo(String value) {
            this.cycleNo = value;
        }

        /**
         * Gets the value of the clearingType property.
         *
         * @return possible object is {@link Byte }
         *
         */
        public String getClearingType() {
            return clearingType;
        }

        /**
         * Sets the value of the clearingType property.
         *
         * @param value allowed object is {@link Byte }
         *
         */
        public void setClearingType(String value) {
            this.clearingType = value;
        }

        /**
         * Gets the value of the returnReason property.
         *
         * @return possible object is {@link Byte }
         *
         */
        public String getReturnReason() {
            return returnReason;
        }

        /**
         * Sets the value of the returnReason property.
         *
         * @param value allowed object is {@link Byte }
         *
         */
        public void setReturnReason(String value) {
            this.returnReason = value;
        }

        /**
         * Gets the value of the returnReasonComment property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getReturnReasonComment() {
            return returnReasonComment;
        }

        /**
         * Sets the value of the returnReasonComment property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setReturnReasonComment(String value) {
            this.returnReasonComment = value;
        }

        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content
         * contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="BOFDRoutNo" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="BOFDBusDate" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="DepositorAcct" type="{http://www.w3.org/2001/XMLSchema}long" />
         *       &lt;attribute name="IFSC" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class AddendA {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "BOFDRoutNo")
            protected String bofdRoutNo;
            @XmlAttribute(name = "BOFDBusDate")
            protected String bofdBusDate;
            @XmlAttribute(name = "DepositorAcct")
            protected String depositorAcct;
            @XmlAttribute(name = "IFSC")
            protected String ifsc;

            /**
             * Gets the value of the value property.
             *
             * @return possible object is {@link String }
             *
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             *
             * @param value allowed object is {@link String }
             *
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the bofdRoutNo property.
             *
             * @return possible object is {@link Integer }
             *
             */
            public String getBOFDRoutNo() {
                return bofdRoutNo;
            }

            /**
             * Sets the value of the bofdRoutNo property.
             *
             * @param value allowed object is {@link Integer }
             *
             */
            public void setBOFDRoutNo(String value) {
                this.bofdRoutNo = value;
            }

            /**
             * Gets the value of the bofdBusDate property.
             *
             * @return possible object is {@link Integer }
             *
             */
            public String getBOFDBusDate() {
                return bofdBusDate;
            }

            /**
             * Sets the value of the bofdBusDate property.
             *
             * @param value allowed object is {@link Integer }
             *
             */
            public void setBOFDBusDate(String value) {
                this.bofdBusDate = value;
            }

            /**
             * Gets the value of the depositorAcct property.
             *
             * @return possible object is {@link Long }
             *
             */
            public String getDepositorAcct() {
                return depositorAcct;
            }

            /**
             * Sets the value of the depositorAcct property.
             *
             * @param value allowed object is {@link Long }
             *
             */
            public void setDepositorAcct(String value) {
                this.depositorAcct = value;
            }

            /**
             * Gets the value of the ifsc property.
             *
             * @return possible object is {@link String }
             *
             */
            public String getIFSC() {
                return ifsc;
            }

            /**
             * Sets the value of the ifsc property.
             *
             * @param value allowed object is {@link String }
             *
             */
            public void setIFSC(String value) {
                this.ifsc = value;
            }
        }
    }
}
